php-enqueue/enqueue-dev

- docs/bundle/config_reference.md
- pkg/amqp-ext/AmqpConnectionFactory.php
- pkg/amqp-ext/AmqpContext.php
- pkg/amqp-ext/Symfony/AmqpTransportFactory.php
- pkg/amqp-ext/Symfony/RabbitMqAmqpTransportFactory.php
- pkg/amqp-ext/Tests/AmqpConnectionFactoryTest.php
- pkg/amqp-ext/Tests/AmqpContextTest.php
- pkg/amqp-ext/Tests/Symfony/AmqpTransportFactoryTest.php
- pkg/amqp-ext/Tests/Symfony/RabbitMqAmqpTransportFactoryTest.php
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Tests/Unit/EnqueueBundleTest.php
- pkg/enqueue-bundle/Tests/Unit/Mocks/FooTransportFactory.php
- pkg/enqueue/Symfony/DefaultTransportFactory.php
- pkg/enqueue/Symfony/NullTransportFactory.php
- pkg/enqueue/Symfony/TransportFactoryInterface.php
- pkg/enqueue/Tests/Symfony/NullTransportFactoryTest.php
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/StompContext.php
- pkg/stomp/Symfony/StompTransportFactory.php
- pkg/stomp/Tests/StompConnectionFactoryTest.php
- pkg/stomp/Tests/StompContextTest.php
- pkg/stomp/Tests/Symfony/RabbitMqStompTransportFactoryTest.php
- pkg/stomp/Tests/Symfony/StompTransportFactoryTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/4
> [amqp] introduce lazy context.

- pkg/amqp-ext/AmqpConsumer.php
- pkg/amqp-ext/AmqpContext.php
- pkg/amqp-ext/AmqpMessage.php
- pkg/amqp-ext/Buffer.php
- pkg/amqp-ext/Tests/AmqpConsumerTest.php
- pkg/amqp-ext/Tests/AmqpContextTest.php
- pkg/amqp-ext/Tests/AmqpMessageTest.php
- pkg/amqp-ext/Tests/AmqpProducerTest.php
- pkg/amqp-ext/Tests/BufferTest.php
Sometimes its possible to get a message of another consumer, if there
are several on same channel.
fixes https://github.com/php-enqueue/enqueue-dev/issues/13
> [amqp] Put in buffer not our message. Continue consumption. 

- docs/bundle/message_processor.md
- docs/consumption/message_processor.md
- docs/index.md
fixes https://github.com/php-enqueue/enqueue-dev/issues/23
> [doc] Add docs about message processors.

- pkg/fs/Client/FsDriver.php
- pkg/fs/Tests/Driver/FsDriverTest.php
> fix fsdriver router topic name

- pkg/enqueue/Consumption/ChainExtension.php
- pkg/enqueue/Consumption/EmptyExtensionTrait.php
- pkg/enqueue/Consumption/ExtensionInterface.php
- pkg/enqueue/Consumption/QueueConsumer.php
- pkg/enqueue/Tests/Consumption/ChainExtensionTest.php
- pkg/enqueue/Tests/Consumption/EmptyExtensionTraitTest.php
- pkg/enqueue/Tests/Consumption/QueueConsumerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/43
> [consumption] Add onResult extension point.

- docs/bundle/cli_commands.md
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/enqueue/Symfony/Consumption/ContainerAwareConsumeMessagesCommand.php
- pkg/enqueue/Tests/Symfony/Consumption/ContainerAwareConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/Mock/QueueSubscriberProcessor.php
Aslo adds ability to bind the processor to several queues at once.  Fixes https://github.com/php-enqueue/enqueue-dev/issues/53
> [consumption] Add support of QueueSubscriberInterface to transport consume command.

- pkg/fs/FsContext.php
- pkg/fs/Tests/Functional/FsContextTest.php
fixes https://github.com/symfony/recipes-contrib/pull/16#discussion_r116027232
> [fs] Filesystem transport must create a storage dir if it does not exists.

- composer.json
- pkg/enqueue/Tests/Functions/DsnToConnectionFactoryFunctionTest.php
- pkg/enqueue/Tests/Functions/DsnToContextFunctionTest.php
- pkg/enqueue/composer.json
- pkg/enqueue/functions.php
- pkg/enqueue/functions_include.php
```php
<?php
namespace Enqueue;
/**
* amqp://
* amqp://user:pass@example.com:10000/%2f
* file://foo/bar/baz
* null://
*
* and others redis, amazon sqs, stomp, mysql+doctrine etc
*/
$c = dsn_to_context('amqp://');
// These functions are  not a part of this PR but could be added later. Just an example of how dsn_to_context could be used. 
send_to_queue($c, 'a_queue_name', 'Hello world');
$message = receive($c);
```
> Add dsn_to_connection_factory and dsn_to_context functions.

- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/EnqueueBundleTest.php
- pkg/enqueue/Symfony/DefaultTransportFactory.php
- pkg/enqueue/Tests/Symfony/DefaultTransportFactoryTest.php
- pkg/enqueue/composer.json
ref https://github.com/symfony/recipes-contrib/pull/16
> [bundle] Set null transport as default. Prevent errors on bundle install.

- composer.json
- docs/bundle/message_producer.md
- docs/index.md
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/Resources/config/client.yml
- pkg/enqueue-bundle/Resources/config/extensions/flush_spool_producer_extension.yml
- pkg/enqueue-bundle/Tests/Functional/Client/SpoolProducerTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
- pkg/enqueue/Client/ConsumptionExtension/FlushSpoolProducerExtension.php
- pkg/enqueue/Client/SpoolProducer.php
- pkg/enqueue/Symfony/Client/FlushSpoolProducerListener.php
- pkg/enqueue/Tests/Client/ConsumptionExtension/FlushSpoolProducerExtensionTest.php
- pkg/enqueue/Tests/Client/SpoolProducerTest.php
- pkg/enqueue/Tests/Symfony/Client/FlushSpoolProducerListenerTest.php
- pkg/enqueue/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/91, required by https://github.com/php-enqueue/enqueue-dev/pull/86
For Symfony developers, it works just out of the box. The spool producer (enqueue.spool_producer service) is flushed on `kernel.terminate` and `console.terminate` events.
> [client] SpoolProducer

- pkg/enqueue/Consumption/Exception/InvalidArgumentException.php
- pkg/enqueue/Tests/Functions/DsnToConnectionFactoryFunctionTest.php
- pkg/enqueue/Tests/Functions/DsnToContextFunctionTest.php
- pkg/fs/FsConnectionFactory.php
- pkg/fs/Tests/FsConnectionFactoryConfigTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/99
> [transport] Fs transport dsn must contain one extra "/"

- docker-compose.yml
- pkg/dbal/DbalConnectionFactory.php
- pkg/dbal/DbalContext.php
- pkg/dbal/Symfony/DbalTransportFactory.php
- pkg/dbal/Tests/DbalConnectionFactoryConfigTest.php
- pkg/dbal/Tests/DbalConnectionFactoryTest.php
- pkg/dbal/Tests/Symfony/DbalTransportFactoryTest.php
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/Tests/Functional/App/CustomAppKernel.php
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/enqueue/Symfony/DefaultTransportFactory.php
- pkg/enqueue/Tests/Functions/DsnToConnectionFactoryFunctionTest.php
- pkg/enqueue/Tests/Symfony/DefaultTransportFactoryTest.php
- pkg/enqueue/functions.php
- pkg/stomp/Symfony/StompTransportFactory.php
ref https://github.com/php-enqueue/enqueue-dev/issues/87
> [dbal] Add DSN support.

- pkg/amqp-ext/AmqpContext.php
Calling AmqpContext::declareQueue() now returns an integer holding the queue message count.
See #64.
> Calling AmqpContext::declareQueue() now returns an integer holding the queue message count

- .travis.yml
- pkg/enqueue-bundle/Tests/Functional/App/TestAsyncListener.php
- pkg/enqueue-bundle/Tests/Functional/App/TestAsyncSubscriber.php
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/enqueue/Symfony/DefaultTransportFactory.php
ref https://github.com/php-enqueue/enqueue-dev/pull/106
> [bundle] Fix "Incompatible use of dynamic environment variables "ENQUEUE_DSN" found in parameters."

- pkg/amqp-ext/AmqpConnectionFactory.php
- pkg/amqp-ext/AmqpConsumer.php
- pkg/amqp-ext/AmqpContext.php
- pkg/amqp-ext/Tests/AmqpConnectionFactoryConfigTest.php
- pkg/amqp-ext/Tests/AmqpConsumerTest.php
- pkg/amqp-ext/Tests/AmqpContextTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/110
> [amqp] Add ability to choose what receive method to use: basic_get or basic_consume.

- pkg/enqueue-bundle/DependencyInjection/Compiler/ExtractProcessorTagSubscriptionsTrait.php
- pkg/enqueue-bundle/Resources/config/client.yml
- pkg/enqueue-bundle/Tests/Functional/App/TestCommandSubscriberProcessor.php
- pkg/enqueue-bundle/Tests/Functional/App/config/config.yml
- pkg/enqueue-bundle/Tests/Functional/Client/ProducerV2Test.php
- pkg/enqueue-bundle/Tests/Functional/QueuesCommandTest.php
- pkg/enqueue-bundle/Tests/Functional/TopicsCommandTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildClientRoutingPassTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildProcessorRegistryPassTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildQueueMetaRegistryPassTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildTopicMetaSubscribersPassTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/EmptyCommandSubscriber.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/InvalidCommandSubscriber.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/OnlyCommandNameSubscriber.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/ProcessorNameCommandSubscriber.php
- pkg/enqueue/Client/CommandSubscriberInterface.php
- pkg/enqueue/Client/Config.php
- pkg/enqueue/Client/Producer.php
- pkg/enqueue/Client/ProducerV2.php
- pkg/enqueue/Client/ProducerV2Interface.php
- pkg/enqueue/Client/RouterProcessor.php
- pkg/enqueue/Tests/Client/RouterProcessorTest.php
- pkg/stomp/Tests/Functional/StompCommonUseCasesTest.php
* Events 1 to many
* Commands 1 to 1 with possibility to get result (optionally)
ref https://github.com/php-enqueue/enqueue-dev/issues/105
A few examples:
* Send an event (same as before except the method name, instead of calling `send` use `sendEvent`.
```php
<?php
namespace Acme;
use Enqueue\Client\TopicSubscriberInterface;
use Enqueue\Psr\PsrContext;
use Enqueue\Psr\PsrMessage;
use Enqueue\Psr\PsrProcessor;
/** @var \Enqueue\Client\ProducerV2Interface $producer */
class FooProcessor implements PsrProcessor, TopicSubscriberInterface
{
public function process(PsrMessage $message, PsrContext $context)
{
return self::ACK;
}
public static function getSubscribedTopics()
{
return ['aFooTopic'];
}
}
$producer->sendEvent('aFooTopic', 'aMessage');
```
* Send command. Fire and forget scenario …
> [RFC][client] Add ability to send events or commands.

- docs/bundle/message_processor.md
- pkg/enqueue-bundle/DependencyInjection/Compiler/BuildExclusiveCommandsExtensionPass.php
- pkg/enqueue-bundle/DependencyInjection/Compiler/ExtractProcessorTagSubscriptionsTrait.php
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Resources/config/extensions/exclusive_command_extension.yml
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildExclusiveCommandsExtensionPassTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/ExclusiveButQueueNameHardCodedCommandSubscriber.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/Mock/ExclusiveCommandSubscriber.php
- pkg/enqueue-bundle/Tests/Unit/EnqueueBundleTest.php
- pkg/enqueue/Client/CommandSubscriberInterface.php
- pkg/enqueue/Client/ConsumptionExtension/ExclusiveCommandExtension.php
- pkg/enqueue/Tests/Client/ConsumptionExtension/ExclusiveCommandExtensionTest.php
In this case you are able to send messages to a comand's queue without
any special message properties.
> [client] Add ability to define a command as exclusive

- .travis.yml
- composer.json
It fixes tests currently broken in master
> [composer] Add extensions to platform config.

- pkg/amqp-ext/AmqpContext.php
- pkg/amqp-lib/AmqpConnectionFactory.php
- pkg/amqp-lib/AmqpContext.php
- pkg/amqp-lib/Tests/AmqpConnectionFactoryConfigTest.php
- pkg/amqp-lib/Tests/AmqpContextTest.php
- pkg/amqp-lib/Tests/Spec/AmqpContextTest.php
ref https://github.com/queue-interop/amqp-interop/issues/6
> [Amqp] Qos

- pkg/enqueue-bundle/DependencyInjection/Configuration.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
- pkg/simple-client/SimpleClientContainerExtension.php
- pkg/test/RetryTrait.php
It fixes issues with fs transport when client's default config is used.
fixes https://github.com/php-enqueue/enqueue-dev/issues/135
> [client] Use default as router topic.

- pkg/enqueue-bundle/DependencyInjection/Compiler/BuildClientRoutingPass.php
- pkg/enqueue-bundle/Resources/config/client.yml
- pkg/enqueue-bundle/Tests/Functional/App/config/custom-config.yml
- pkg/enqueue-bundle/Tests/Functional/TestCommandProcessor.php
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/Compiler/BuildClientRoutingPassTest.php
cleaned version of https://github.com/php-enqueue/enqueue-dev/pull/161 plus tests.
> Client fix command routing

- pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig
MaxDepth was introduced in Symfony 3.2 so to maintain 2.8 compatibility
we should remove this option.
Fixes: #158
> Remove maxDepth option on profiler dump.

- pkg/enqueue/Consumption/QueueConsumer.php
- pkg/enqueue/Tests/Consumption/QueueConsumerTest.php
- pkg/rdkafka/Tests/Spec/RdKafkaSendToAndReceiveFromTopicTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/159#issuecomment-321199613
> [consumption] adjust receive and idle timeouts

- pkg/dbal/DbalConsumer.php
- pkg/dbal/Tests/DbalConsumerTest.php
- pkg/redis/RedisConsumer.php
Not all drivers supported FOR UPDATE queries so this change changes the
raw SQL to use the query builder thus allowing DBAL to construct the
appropriate query per platform. It then grabs the SQL and appends the
read lock SQL but grabs the SQL part from the correct platform as
to not break portability.
> Use Query Builder for better support across platforms.

- pkg/rdkafka/RdKafkaContext.php
Hey-hey 👋 
Copy-paste typo in RdKafkaContext configuration.
> Fix typo in configuration parameter

- pkg/sqs/Tests/Spec/SqsProducerTest.php
- pkg/sqs/Tests/Spec/SqsSendAndReceiveDelayedMessageFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromTopicTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/179
> [sqs] Skip tests if no amazon credentinals present.

- pkg/enqueue-bundle/DependencyInjection/Compiler/BuildTopicMetaSubscribersPass.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/172
> [bundle] do not use client's related stuff if it is disabled

- pkg/enqueue/Consumption/QueueConsumer.php
- pkg/enqueue/Symfony/Client/ConsumeMessagesCommand.php
- pkg/enqueue/Symfony/Consumption/ConsumeMessagesCommand.php
- pkg/enqueue/Symfony/Consumption/ContainerAwareConsumeMessagesCommand.php
- pkg/enqueue/Tests/Consumption/QueueConsumerTest.php
- pkg/enqueue/Tests/Symfony/Client/ConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/ConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/ContainerAwareConsumeMessagesCommandTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/177
> [consumption] Do not close context.

- .travis.yml
- pkg/gps/Tests/Client/GpsDriverTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/141
> [phpstan] update to 0.8 version

- docs/transport/kafka.md
- pkg/rdkafka/JsonSerializer.php
- pkg/rdkafka/RdKafkaConsumer.php
- pkg/rdkafka/RdKafkaContext.php
- pkg/rdkafka/RdKafkaMessage.php
- pkg/rdkafka/RdKafkaProducer.php
- pkg/rdkafka/Serializer.php
- pkg/rdkafka/SerializerAwareTrait.php
- pkg/rdkafka/Tests/JsonSerializerTest.php
- pkg/rdkafka/Tests/RdKafkaConsumerTest.php
- pkg/rdkafka/Tests/RdKafkaContextTest.php
- pkg/rdkafka/Tests/RdKafkaProducerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/187
TODO:
* ~~upd eqnueue bundle~~
> [rdkafka] Add abilito change the way a message is serialized.

- pkg/fs/FsConsumer.php
- pkg/fs/Tests/Functional/FsConsumerTest.php
The #181 introduces a bug that corrupts the file structure and makes it
impossible to read.
Address https://github.com/php-enqueue/enqueue-dev/issues/202.
> [fs] fix bugs introduced in #181.

- docs/transport/redis.md
- docs/transport/sqs.md
- docs/transport/stomp.md
- pkg/amqp-bunny/AmqpConnectionFactory.php
- pkg/amqp-bunny/Tests/AmqpConnectionFactoryConfigTest.php
- pkg/amqp-ext/AmqpConnectionFactory.php
- pkg/amqp-ext/Tests/AmqpConnectionFactoryConfigTest.php
- pkg/amqp-lib/AmqpConnectionFactory.php
- pkg/amqp-lib/Tests/AmqpConnectionFactoryConfigTest.php
- pkg/enqueue/Symfony/DefaultTransportFactory.php
- pkg/enqueue/Tests/Functions/DsnToConnectionFactoryFunctionTest.php
- pkg/enqueue/Tests/Functions/DsnToContextFunctionTest.php
- pkg/enqueue/Tests/Symfony/DefaultTransportFactoryTest.php
- pkg/enqueue/functions.php
- pkg/redis/RedisConnectionFactory.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
- pkg/redis/Tests/RedisConnectionFactoryTest.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
- pkg/stomp/Tests/StompConnectionFactoryTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/87
> [redis] add dsn support for redis transport.

- pkg/enqueue-bundle/Resources/config/client.yml
Fix the error below when attempting to open the profiler in a Symfony Flex project : 
`The profiler template "EnqueueBundle:Profiler:panel.html.twig" for data collector "enqueue.message_queue" does not exist.`
> Fixes the notation for Twig template names in the data collector

- docs/elastica-bundle/populate-command-optimization.md
If `client: ~` is not added you will get an error `The service "fos_elastica.provider.app.channel" has a dependency on a non-existent service "enqueue.client.producer".` because the client services are not loaded until you add `client: ~`
> Missing client configuration in the documentation

- .gitignore
- README.md
- bin/build-rabbitmq-image.sh
- bin/build-rabbitmq-ssl-image.sh
- bin/test
- docker-compose.yml
- docs/bundle/config_reference.md
- docs/transport/amqp.md
- docs/transport/amqp_lib.md
- pkg/amqp-bunny/AmqpConnectionFactory.php
- pkg/amqp-bunny/Tests/AmqpConnectionFactoryTest.php
- pkg/amqp-bunny/Tests/Spec/AmqpSslSendToAndReceiveFromQueueTest.php
- pkg/amqp-ext/AmqpConnectionFactory.php
- pkg/amqp-ext/Tests/AmqpConnectionFactoryTest.php
- pkg/amqp-ext/Tests/Spec/AmqpSslSendToAndReceiveFromQueueTest.php
- pkg/amqp-lib/AmqpConnectionFactory.php
- pkg/amqp-lib/Tests/AmqpConnectionFactoryTest.php
- pkg/amqp-lib/Tests/Spec/AmqpSslSendToAndReceiveFromQueueTest.php
- pkg/amqp-tools/ConnectionConfig.php
- pkg/amqp-tools/Tests/ConnectionConfigTest.php
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/enqueue/Symfony/AmqpTransportFactory.php
- pkg/enqueue/Tests/Functions/DsnToConnectionFactoryFunctionTest.php
- pkg/enqueue/Tests/Symfony/AmqpTransportFactoryTest.php
- pkg/enqueue/functions.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/147
> [amqp] Add AMQP secure (SSL) connections support

- pkg/rdkafka/RdKafkaProducer.php
- pkg/rdkafka/Tests/RdKafkaProducerTest.php
Currently the `RdKafkaProducer` is serializing just the message, which I guess us fine for JSON serialization.
But when you want to use an AvroSerializer that integrates with the Confluent Platform, it is possible to use complex types as keys as well, which in turn means that keys need to be serialized, too.
This change leverages the mutability of the Message by shifting the `getKey` method call after the call to the Serializer.
> [RdKafka] Enable serializers to serialize message keys

- pkg/enqueue/Client/ConsumptionExtension/SetRouterPropertiesExtension.php
- pkg/enqueue/Tests/Client/ConsumptionExtension/SetRouterPropertiesExtensionTest.php
> Changes SetRouterPropertiesExtension to use the driver to generate the queue name

- pkg/enqueue/Consumption/QueueConsumer.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/260
use https://github.com/formapro-forks/enqueue/tree/consumption-amqp-on-idle-not-called for tests in your app.
> [consumption][amqp] onIdle is never called.

- pkg/enqueue/Consumption/QueueConsumer.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/259
> [consumption] fix context is missing message on exception.

- pkg/redis/RedisMessage.php
- pkg/redis/Symfony/RedisTransportFactory.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
- pkg/redis/Tests/Symfony/RedisTransportFactoryTest.php
Add configuration to use dsn configuration in symfony bundle.
> [Redis] add dsn support for symfony bundle.

- pkg/rdkafka/RdKafkaTopic.php
- pkg/rdkafka/Tests/RdKafkaProducerTest.php
- pkg/rdkafka/Tests/RdKafkaTopicTest.php
this is alternative to the same problem as described here https://github.com/php-enqueue/enqueue-dev/pull/256
the branch to use in app could be found here https://github.com/formapro-forks/rdkafka/tree/rdkafka-topic-default-config
@tPl0ch  could you please test it?
> [rdkafka] do not pass config if it was not set explisitly.

- pkg/fs/CannotObtainLockException.php
- pkg/fs/FsContext.php
- pkg/fs/LegacyFilesystemLock.php
- pkg/fs/Lock.php
- pkg/fs/Tests/FsContextTest.php
- pkg/fs/Tests/LegacyFilesystemLockTest.php
a step towards https://github.com/php-enqueue/enqueue-dev/pull/269, ref https://github.com/php-enqueue/enqueue-dev/issues/166
> [fs] Copy past Symfony's LockHandler (not awailable in Sf4).

- pkg/enqueue-bundle/Tests/Functional/App/CustomAppKernel.php
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/sqs/SqsContext.php
- pkg/stomp/StompConnectionFactory.php
While working on https://github.com/php-enqueue/enqueue-dev/pull/269 PR I found out that use cases didn't work properly. 
This PR fixes it.
> [bundle] Apparently the use case tests have never worked properly.

- docs/consumption/message_processor.md
fixes https://github.com/php-enqueue/enqueue-dev/issues/240
> [doc][skip ci] Add processor examples, notes on exception and more.

- docs/client/extensions.md
- docs/index.md
fixes https://github.com/php-enqueue/enqueue-dev/issues/73
> [doc][skip ci] add doc for client on send extensions.

- composer.json
- pkg/dbal/DbalConsumer.php
- pkg/dbal/Tests/DbalConsumerTest.php
- pkg/dbal/Tests/Spec/DbalRequeueMessageTest.php
- pkg/dbal/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/290
> [dbal] Fix message re-queuing. Reuse producer for it.

- pkg/dbal/DbalContext.php
I know that you are working on #280 but for current users of Enqueue, it is very inconvenient to manually edit the package to fix this bug and it also makes deploying/CI difficult. Can you release this as 0.8.12?
> Fix reversed logic for native UUID detection

- pkg/enqueue/Consumption/Extension/SignalExtension.php
When handling a signal, a logger is used to log the catched signals. However, the logger can sometimes be uninitialised, which resulted in errors.
> Check if logger exists

- pkg/rdkafka/RdKafkaConsumer.php
- pkg/rdkafka/RdKafkaContext.php
- pkg/rdkafka/Tests/RdKafkaConsumerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/306
> [rdkafka] Don't do unnecessary subscribe\unsubscribe on every receive call

- docs/transport/kafka.md
- pkg/rdkafka/RdKafkaConsumer.php
- pkg/rdkafka/Tests/RdKafkaConsumerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/305
> [kafka] add ability to set offset.

- pkg/amqp-bunny/AmqpContext.php
- pkg/amqp-lib/AmqpContext.php
- pkg/amqp-tools/SignalSocketHelper.php
- pkg/amqp-tools/Tests/SignalSocketHelperTest.php
- pkg/enqueue/Consumption/Extension/SignalExtension.php
- pkg/enqueue/Symfony/AmqpTransportFactory.php
- pkg/enqueue/Tests/Symfony/AmqpTransportFactoryTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/300
> [amqp] Fix socket and signal issue.

- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
I encountered a problem with using DSN-based configuration in Symfony 4, where the 'dsn' value was always being passed as an array key. The constructor did not properly handle this, and the primary symptom of this was a constant complaint that the 'region' was not set, even though it was present in the DSN.
> [Sqs] Allow array-based DSN configuration

- pkg/dbal/DbalConnectionFactory.php
- pkg/dbal/DbalConsumer.php
- pkg/dbal/DbalContext.php
- pkg/dbal/DbalProducer.php
- pkg/dbal/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/279
fixes https://github.com/php-enqueue/enqueue-dev/issues/276
> [0.9][BC break][dbal] Store UUIDs as binary data. Improves performance

- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
- pkg/enqueue/Symfony/MissingTransportFactory.php
- pkg/enqueue/Tests/Symfony/MissingTransportFactoryTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/333
The PR improves a message a develoepr sees when a desired package is not installed.
Instead of:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized option "amqp" under "enqueue.transport"
```
He would see:
> [bundle][dx] Add a message that suggest installing a pkg to use the transport.

- pkg/job-queue/composer.json
just the tests needs symfony/framework-bundle
> Moved symfony/framework-bundle to require-dev

- docs/bundle/async_events.md
Had a slight problem reading documentation early in the morning, realized there were some grammatical changes that would make this a bit easier to read.
Resolves #363 within the `async_events.md` document.
> Modify async_events.md grammar

- docs/client/quick_tour.md
- docs/client/supported_brokers.md
- docs/quick_tour.md
- pkg/simple-client/SimpleClient.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/351
> [client][skip ci] Explain meaning of sendEvent, sendCommand methods.

- bin/dev
- docs/transport/redis.md
- pkg/redis/RedisConnectionFactory.php
- pkg/redis/Symfony/RedisTransportFactory.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
- pkg/redis/Tests/RedisConnectionFactoryTest.php
- pkg/redis/Tests/Symfony/RedisTransportFactoryTest.php
- pkg/simple-client/SimpleClient.php
fixes https://github.com/php-enqueue/enqueue-dev/pull/368, https://github.com/php-enqueue/enqueue-dev/issues/367, https://github.com/php-enqueue/enqueue-dev/pull/350, https://github.com/php-enqueue/enqueue-dev/issues/349, https://github.com/php-enqueue/enqueue-dev/pull/346, https://github.com/php-enqueue/enqueue-dev/issues/341
> [Redis] Add ability to pass Redis instance to connection factory

- pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig
fixes https://github.com/php-enqueue/enqueue-dev/issues/355
> [symfony] Print command name

- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Tests/Unit/EnqueueBundleTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/383
> [bundle] fix for "Transport factory with such name already added"

- pkg/job-queue/JobRunner.php
- pkg/job-queue/Tests/JobRunnerTest.php
Fixes a condition that occurs when a running job triggers an uncaught exception. The job is left in a “running” state instead of “failed” and future jobs with the same name are not allowed to run.
Fixes issue #385
> Clean up when a job triggers an exception

- pkg/fs/FsConsumer.php
- pkg/fs/FsProducer.php
- pkg/fs/Tests/Functional/FsConsumerTest.php
- pkg/fs/Tests/Functional/FsProducerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/390, https://github.com/php-enqueue/enqueue-dev/issues/387
> [fs] Escape delimiter symbols. 

- pkg/enqueue-bundle/Consumption/Extension/DoctrinePingConnectionExtension.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrinePingConnectionExtensionTest.php
Issue appears when symfony app has more than one connection defined. $connection->ping() always tries to open connection regardless it was used previously or not.
> [bundle] Don't ping DBAL connection if it wasn't opened

- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
So it can be used with Symfony ^4
> [bundle] Make TraceableProducer service public

- docs/bundle/config_reference.md
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/Symfony/StompTransportFactory.php
- pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
- pkg/stomp/Tests/Symfony/RabbitMqStompTransportFactoryTest.php
- pkg/stomp/Tests/Symfony/StompTransportFactoryTest.php
Allow to enable SSL, depend the uri scheme on that. Fully backwards compatible.
> Allow to enable SSL in StompConnectionFactory

- pkg/dbal/DbalConnectionFactory.php
- pkg/dbal/Tests/DbalConnectionFactoryConfigTest.php
https://github.com/php-enqueue/dbal/pull/2
> PHP_URL_SCHEME doesn't support underscores

- docs/cookbook/symfony/how-to-change-consume-command-logger.md
This pull request updates "back to index" link to https://github.com/php-enqueue/enqueue-dev/blob/master/docs/index.md Previous link was  linked to 404 page.
> Update of "back to index" link

- docs/bundle/config_reference.md
- docs/transport/sqs.md
- pkg/enqueue-bundle/Tests/Functional/App/config/custom-config.yml
- pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/Symfony/SqsTransportFactory.php
- pkg/sqs/Tests/SqsConnectionFactoryTest.php
- pkg/sqs/Tests/Symfony/SqsTransportFactoryTest.php
This is a work-in-progress and relates to #443.
Many thanks to @rpkamp and @dbrumann for their assistance!
> WIP: Add support for using a pre-configured client with the SQS driver

- pkg/enqueue/Consumption/Extension/NicenessExtension.php
- pkg/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php
- pkg/enqueue/Tests/Consumption/Extension/NicenessExtensionTest.php
- pkg/enqueue/Tests/Symfony/Client/ConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/ConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/ContainerAwareConsumeMessagesCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/LimitsExtensionsCommandTraitTest.php
> [consumption] add process niceness extension

- pkg/simple-client/SimpleClient.php
- pkg/simple-client/Tests/SimpleClientTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/483
> simple client dsn issue

- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
This will allow to Symfony users that have autoconfigure/autowiring enabled to avoid defining
explicitly the processor service and its tag. Now, the symfony container does it automatically.
> Add autoconfigure for services extending PsrProcess interface

- pkg/rdkafka/RdKafkaConsumer.php
- pkg/rdkafka/Tests/RdKafkaConsumerTest.php
With `assign` it is not possible to use the rebalancing from Kafka. So if no offset is set we use `subscribe` and rebalancing is possible and otherwise if a offset is set we are using assign.
> Allow either subscribe or assign in RdKafkaConsumer

- pkg/enqueue/composer.json
Prevents errors of Class 'Enqueue\Dsn\Dsn' not found.
> Fixing composer.json to require enqueue/dsn

- pkg/enqueue/Client/Driver/RdKafkaDriver.php
- pkg/enqueue/Client/Driver/RedisDriver.php
- pkg/enqueue/Tests/Client/Driver/RdKafkaDriverTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/557
> [rdkafka] Use default queue as router topic

- pkg/enqueue-bundle/DependencyInjection/Configuration.php
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/EnqueueBundle.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
- pkg/enqueue/Client/DriverFactory.php
- pkg/enqueue/Client/Resources.php
- pkg/enqueue/Symfony/Client/DependencyInjection/ClientFactory.php
- pkg/enqueue/Symfony/Client/DependencyInjection/FormatClientNameTrait.php
- pkg/enqueue/Symfony/DependencyInjection/BuildConsumptionExtensionsPass.php
- pkg/enqueue/Symfony/DependencyInjection/BuildProcessorRegistryPass.php
- pkg/enqueue/Symfony/DependencyInjection/FormatTransportNameTrait.php
- pkg/enqueue/Tests/Client/ResourcesTest.php
- pkg/enqueue/Tests/Symfony/DependencyInjection/BuildConsumptionExtensionsPassTest.php
- pkg/enqueue/Tests/Symfony/DependencyInjection/BuildProcessorRegistryPassTest.php
These configuration are possible:
* one default transport
```yaml
enqueue: '%env(ENQUEUE_DSN)%'
```
* one default transport
```yaml
enqueue: 
transport: '%env(ENQUEUE_DSN)%'
```
* one default transport
```yaml
enqueue: 
transport: 
default: '%env(ENQUEUE_DSN)%'
```
* several transports
```yaml
enqueue: 
transport: 
foo: '%env(AMQP_DSN)%'
bar: 
dsn: '%env(SQS_DSN)%'
baz: '%env(SQS_DSN)%'
```
> Bundle multi transport configuration

- pkg/rdkafka/RdKafkaConsumer.php
Allow either to use assign or subscribe
With `assign` it is not possible to use the rebalancing from Kafka. So if no offset is set we use `subscribe` and rebalancing is possible and otherwise if a offset is set we are using assign.
@see commit d2fa17881fcc2c523b8277f3ba30d1d9caeff667
@see https://github.com/php-enqueue/enqueue-dev/issues/570
> [rdkafka] Backport changes to topic subscription

- composer.json
- pkg/redis/RedisConnectionFactory.php
- pkg/redis/composer.json
Added check on phpredis or predis availability
fixes https://github.com/php-enqueue/enqueue-dev/issues/551
> Removed predis from composer.json

- pkg/job-queue/Doctrine/JobStorage.php
- pkg/job-queue/Tests/Doctrine/JobStorageTest.php
After a Job triggers a Doctrine exception, and handles it, the EntityManager still remains closed and JobStorage can't persist changes. This fix resets the Manager after such an occurrence.
> Allow JobStorage to reset the EntityManager

- docs/transport/dbal.md
- pkg/dbal/DbalConsumer.php
- pkg/dbal/DbalConsumerHelperTrait.php
- pkg/dbal/DbalContext.php
- pkg/dbal/DbalMessage.php
- pkg/dbal/DbalProducer.php
- pkg/dbal/DbalSubscriptionConsumer.php
- pkg/dbal/Tests/DbalConsumerTest.php
- pkg/dbal/Tests/Functional/DbalConsumerTest.php
> [dbal] Introduce redelivery support based on visibility approach. 

- pkg/amqp-lib/AmqpConnectionFactory.php
In order to be able to use the 'ciphers' option (http://php.net/manual/en/context.ssl.php), it needs to be declared in the $sslOptions array, so it can be passed to AMQPSSLConnection.
It will read the value from the 'driver_options' as such:
```
enqueue:
transport:
default: rabbitmq_amqp
rabbitmq_amqp:
...
driver_options:
ciphers: "RSA,DHE,..."
```
> Add support for the 'ciphers' ssl option

- docs/transport/filesystem.md
- pkg/dsn/Dsn.php
- pkg/dsn/Tests/DsnTest.php
- pkg/fs/FsConnectionFactory.php
- pkg/fs/Tests/FsConnectionFactoryConfigTest.php
- pkg/fs/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/610
> [fs] Use enqueue/dsn to parse DSN

- pkg/enqueue/Consumption/FallbackSubscriptionConsumer.php
This follows #625 I created yesterday 
Let's try to explain the issue with further details.
This occurs when using AWS SQS as queue system.
The SQS context doesn't support `SubscriptionConsumer` and throws an exception when calling its `createSubscriptionConsumer()` method. This exception is then caught and is replaced by the fallback subscription consumer.
The `FallbackSubscriptionConsumer` is a basic implementation which loops over a list of subscribers and call on each of them their `receiveNoWait()` method.
This is a cost killer for AWS SQS as this will query for new messages without polling.
Here's an example of the command I run and which leads to this dramatic cost:
`php bin/console enqueue:transport:consume --time-limit=+80seconds --receive-timeout=20000 --idle-timeout=5000 …
> Avoid receiveNoWait when only one subscriber

- pkg/gearman/GearmanProducer.php
- pkg/pheanstalk/PheanstalkProducer.php
- pkg/rdkafka/RdKafkaProducer.php
- pkg/redis/RedisProducer.php
- pkg/stomp/StompProducer.php
The `setPriority` method have to throw a PriorityNotSupportedException
if the feature is not supported.
> Fix wrong exceptions in transports

- pkg/dbal/DbalConsumerHelperTrait.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/638
> [dbal] handle gracefully concurrency issues or 3rd party interruptions. 

- composer.json
- pkg/dbal/DbalConsumerHelperTrait.php
- pkg/dbal/composer.json
addition to https://github.com/php-enqueue/enqueue-dev/pull/640
> [dbal] Use RetryableException, wrap fetchMessage exception to it too.

- docs/dsn.md
- pkg/amqp-tools/ConnectionConfig.php
- pkg/dsn/Dsn.php
- pkg/dsn/QueryBag.php
- pkg/dsn/Tests/DsnTest.php
- pkg/enqueue/Client/DriverFactory.php
- pkg/enqueue/ConnectionFactoryFactory.php
- pkg/fs/FsConnectionFactory.php
- pkg/gps/GpsConnectionFactory.php
- pkg/monitoring/GenericStatsStorageFactory.php
- pkg/monitoring/InfluxDbStorage.php
- pkg/monitoring/WampStorage.php
- pkg/redis/RedisConnectionFactory.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
- pkg/test/RabbitManagementExtensionTrait.php
- pkg/wamp/WampConnectionFactory.php
Parse Cluster DSN:
```php
<?php
use Enqueue\Dsn\Dsn;
$dsns = Dsn::parse('mysql+pdo://user:password@foo:3306,bar:5678/database?connection_timeout=123');
count($dsns); // 2
$dsns[0]->getUser(); // 'user'
$dsns[0]->getPassword(); // 'password'
$dsns[0]->getHost(); // 'foo'
$dsns[0]->getPort(); // 3306
$dsns[1]->getUser(); // 'user'
$dsns[1]->getPassword(); // 'password'
$dsns[1]->getHost(); // 'bar'
$dsns[1]->getPort(); // 5678  
```
Get typed query params:
```php
<?php
use Enqueue\Dsn\Dsn;
$dsn = Dsn::parseFirst('sqs:?decimal=12&octal=0666&float=1.2&bool=1&array[0]=val');
$dsn->getDecimal('decimal'); // 12
$dsn->getOctal('decimal'); // 0666
$dsn->getFloat('float'); // 1.2
$dsn->getBool('bool'); // true
$dsn->getArray('array')->getString(0); // val
$dsn->getArray('array')->toArray(); // …
```
> [dsn] Parse DSN Cluster

- pkg/dsn/Dsn.php
- pkg/dsn/Tests/DsnTest.php
- pkg/enqueue/Client/Resources.php
- pkg/enqueue/Resources.php
- pkg/enqueue/Tests/ResourcesTest.php
- pkg/redis/PRedis.php
- pkg/redis/PhpRedis.php
- pkg/redis/RedisConnectionFactory.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/652, https://github.com/php-enqueue/enqueue-dev/issues/650, https://github.com/php-enqueue/enqueue-dev/issues/648
> Redis dsn and password fixes

- pkg/amqp-lib/AmqpConnectionFactory.php
- pkg/amqp-lib/AmqpContext.php
- pkg/amqp-lib/AmqpSubscriptionConsumer.php
- pkg/amqp-lib/Tests/AmqpContextTest.php
- pkg/amqp-lib/Tests/AmqpSubscriptionConsumerTest.php
- pkg/amqp-lib/Tests/Functional/AmqpSubscriptionConsumerWithHeartbeatOnTickTest.php
- pkg/amqp-lib/composer.json
php-amqplib comes with a heartbeat feature. It does not work at all, unreliable and broken. More in the post [Keeping RabbitMQ connections alive in PHP](https://blog.mollie.com/keeping-rabbitmq-connections-alive-in-php-b11cb657d5fb).
This PR fixes it. You could wrap your long running code into `decalre(ticks=1) {}`. The number of ticks should be adjusted to your needs. Calling it at every tick is not good. 
Please note that it does not fix heartbeat issue if you spent most of the time on IO operation.
```php
<?php
use Enqueue\AmqpLib\AmqpConnectionFactory;
use Interop\Amqp\AmqpConsumer;
use Interop\Amqp\AmqpMessage;
$context = (new AmqpConnectionFactory('amqp:?heartbeat_on_tick=1'))->createContext();
$queue = $context->createQueue('a_queue');
$consumer = $context->createConsumer($queue); …
```
> [amqp][lib] Improve heartbeat handling. Introduce heartbeat on tick. Fixes "Invalid frame type 65" and "Broken pipe or closed connection"

- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/SqsContext.php
- pkg/sqs/Tests/Spec/CreateSqsQueueTrait.php
- pkg/sqs/Tests/Spec/SqsSendAndReceiveDelayedMessageFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromTopicTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromTopicTest.php
- pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveNoWaitFromQueueTest.php
- pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
- pkg/sqs/Tests/SqsConnectionFactoryTest.php
- pkg/sqs/Tests/SqsContextTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/596
> [sqs] Use a queue created in another AWS account.

- pkg/dbal/DbalContext.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/657
https://travis-ci.org/php-enqueue/enqueue-dev/jobs/458362777
```
1)
Enqueue\Dbal\Tests\Functional\DbalConsumerTest::testShouldOrderMessagesWithSamePriorityByPublishedAtDate
InvalidArgumentException: $bytes string should contain 16 characters.
/mqdev/vendor/ramsey/uuid/src/Codec/StringCodec.php:97
/mqdev/vendor/ramsey/uuid/src/UuidFactory.php:188
/mqdev/vendor/ramsey/uuid/src/Uuid.php:632
/mqdev/pkg/dbal/DbalContext.php:155
/mqdev/pkg/dbal/DbalConsumerHelperTrait.php:82
/mqdev/pkg/dbal/DbalConsumer.php:83
/mqdev/vendor/queue-interop/queue-interop/src/Impl/ConsumerPollingTrait.php:42
/mqdev/pkg/dbal/Tests/Functional/DbalConsumerTest.php:95
```
> [dbal] Use ordered bytes time uuid codec on message id decode.

- docs/transport/sqs.md
- pkg/sqs/SqsContext.php
- pkg/sqs/SqsDestination.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToAndReceiveNoWaitFromTopicTest.php
- pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveFromQueueTest.php
- pkg/sqs/Tests/Spec/SqsSendToTopicAndReceiveNoWaitFromQueueTest.php
- pkg/sqs/Tests/SqsContextTest.php
SQS allows to use queues from another account. You could set it globally for all queues via option `queue_owner_aws_account_id` or 
per queue using `SqsDestination::setQueueOwnerAWSAccountId` method.
```php
<?php
use Enqueue\Sqs\SqsConnectionFactory;
// globally for all queues
$factory = new SqsConnectionFactory('sqs:?queue_owner_aws_account_id=awsAccountId');
$context = (new SqsConnectionFactory('sqs:'))->createContext();
// per queue.
$queue = $context->createQueue('foo');
$queue->setQueueOwnerAWSAccountId('awsAccountId');
> [sqs] Add ability to use another aws account per queue.

- docs/transport/sqs.md
- pkg/sqs/SqsClient.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/SqsConsumer.php
- pkg/sqs/SqsContext.php
- pkg/sqs/SqsProducer.php
- pkg/sqs/Tests/SqsClientTest.php
- pkg/sqs/Tests/SqsConnectionFactoryTest.php
- pkg/sqs/Tests/SqsConsumerTest.php
- pkg/sqs/Tests/SqsContextTest.php
- pkg/sqs/Tests/SqsProducerTest.php
ref https://github.com/php-enqueue/enqueue-dev/issues/439
Enqueue SQS provides a generic multi-region support. This enables users to specify which AWS Region to send a command to by setting region on SqsDestination.
You might need it to access SQS FIFO queue because they are not available for all regions. 
If not specified the default region is used. 
```php
<?php
use Enqueue\Sqs\SqsConnectionFactory;
$context = (new SqsConnectionFactory('sqs:?region=eu-west-2'))->createContext();
$queue = $context->createQueue('foo');
$queue->setRegion('us-west-2');
// the request goes to US West (Oregon) Region
$context->declareQueue($queue);
```
> [sqs] Multi region support

- pkg/fs/FsContext.php
Caused by queue-interop package
[ErrorException]
The "Enqueue\Fs\FsMessage" class implements "Interop\Queue\PsrMessage" that is deprecated will be removed in later versions. use one without Psr prefix.
* The Message interface is the root interface of all transport messages. Most message-oriented middleware (MOM) products treat messages as lightweight entities that consist of a header and a payload. The header contains fields used for message routing an
d identification; the payload contains the application data being sent.
* Within this general form, the definition of a message varies significantly across products.
thrown here: https://github.com/ssiergl/enqueue-dev/blob/master/pkg/fs/FsConsumer.php#L131
As discussed in gitter. Without this patch fs transporter is not usable.
> [fs] Do not throw error in jsonUnserialize on deprecation notice

- pkg/mongodb/MongodbConnectionFactory.php
- pkg/mongodb/Tests/MongodbConnectionFactoryTest.php
Fixes this error:
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Enqueue\Mongodb\MongodbConsumer::setPollingInterval() must be of the type integer, string given, called in /var/www/api/vendor/enqueue/mongodb/MongodbContext.php on line 97 in /var/www/api/vendor/enqueue/mongodb/MongodbConsumer.php:40
```
when running `bin/console enqueue:consume` with a DSN with a `polling_interval` parameter
> polling_integer type not correctly handled when using DSN

- pkg/dbal/DbalProducer.php
int must be passed when strict_types is on
> fix: Wrong parameters for Exception

- pkg/enqueue/Client/CommandSubscriberInterface.php
> updated docs

- phpstan.neon
- pkg/async-event-dispatcher/DependencyInjection/Configuration.php
- pkg/enqueue-bundle/DependencyInjection/Configuration.php
- pkg/enqueue/Tests/Symfony/DependencyInjection/TransportFactoryTest.php
- pkg/simple-client/SimpleClient.php
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
> Fix TreeBuilder in Symfony 4.2

- pkg/async-command/DependencyInjection/AsyncCommandExtension.php
- pkg/async-command/Resources/config/services.yml
- pkg/async-command/RunCommandProcessor.php
- pkg/async-command/Tests/RunCommandProcessorTest.php
- pkg/async-event-dispatcher/AsyncProcessor.php
- pkg/async-event-dispatcher/DependencyInjection/AsyncEventDispatcherExtension.php
- pkg/async-event-dispatcher/Resources/config/services.yml
- pkg/enqueue-bundle/Tests/Functional/App/config/config.yml
- pkg/enqueue-bundle/Tests/Functional/Events/AsyncProcessorTest.php
- pkg/enqueue-bundle/Tests/Functional/RoutesCommandTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/690
> Fix async command\event pkgs

- pkg/amqp-tools/ConnectionConfig.php
- pkg/amqp-tools/Tests/ConnectionConfigTest.php
Fix issue #696 parsing vhost like rabbitMQ default (`%2f`)
> [amqp] fix #696 parsing vhost from amqp dsn

- pkg/dbal/DbalConsumerHelperTrait.php
- pkg/dbal/DbalContext.php
- pkg/dbal/DbalProducer.php
- pkg/dbal/Tests/DbalConsumerTest.php
> [dbal] Use string-based UUIDs instead of binary

- pkg/enqueue/Symfony/Consumption/LimitsExtensionsCommandTrait.php
- pkg/enqueue/Tests/Symfony/Consumption/LimitsExtensionsCommandTraitTest.php
Values from CLI comes as strings but extension expects integer, therefore exception is thrown on any value, even correct one.
> [consumption] fix wrong niceness extension param

- pkg/monitoring/composer.json
I removed dev dependency from requirements. Should help for `minimum-stability: stable`  projects.
Composer log:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for enqueue/monitoring ^0.9.1 -> satisfiable by enqueue/monitoring[0.9.1].
- enqueue/monitoring 0.9.1 requires enqueue/dsn 0.9.x-dev -> satisfiable by enqueue/dsn[0.9.x-dev] but these conflict with your requirements or minimum-stability.
```
> Monitoring - Add support for minimum stability - stable

- .gitignore
- pkg/monitoring/InfluxDbStorage.php
I deep dive into one bug on monitoring package, I found that message statistics are not accepted by influxdb (even by 1 year old revision), we always receive message
```
{"error":"unable to parse 'sent-messages,destination=example_topic,command=example_command 1546449295702': invalid field format"}
``` 
Which means that it's not passing influxdb [requirements - LINK](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/). I checked it and yes, we can send empty value, but only if we have some additional fields. In our case we don't have any fields and no value (which is field as well).
1. Try to send request to influxdb with current state:
`curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary …
> Monitoring - Fixed influxdb write on sentMessageStats

- pkg/async-command/DependencyInjection/AsyncCommandExtension.php
- pkg/async-event-dispatcher/DependencyInjection/AsyncEventDispatcherExtension.php
I replaced `queue_prefixed` by `prefix_queue`in command and event DI extension. See https://github.com/php-enqueue/enqueue-dev/issues/690
> Fix async command/event pkgs

- pkg/sqs/SqsClient.php
- pkg/sqs/SqsConsumer.php
- pkg/sqs/Tests/SqsConsumerTest.php
Per #475, current Sqs requeue behaviour deletes the message and create another one.
This is not desirable because SQS lost track of Receive count, hence unable to adopt dead letter queue.
Changes made to terminte visibility timeout instead:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#terminating-message-visibility-timeout
Todo:
> [sqs] Dead Letter Queue Adoption

- pkg/pheanstalk/PheanstalkConsumer.php
Requeuing a message in Beanstalk means to release a reserved message:
https://github.com/beanstalkd/beanstalkd/blob/b5a6f7a23a368ffb31fbf48cdffe95541166d3fa/doc/protocol.txt#L85-L102
If the message is acknowledged beforehand (i.e. deleted), it can't be released anymore.
If you are OK with the modification, I will add a unit test.
> [pheanstalk] Requeuing a message should not acknowledge it beforehand

- pkg/enqueue/Consumption/QueueConsumer.php
We're currently using enqueue 0.9.4 and monolog 1.24.0 in a symfony 4.2.2 project.
We're getting `OutOfMemoryException` when an exception is thrown from a processor. After digging a little bit in the code base, we found that monolog [loops indefinitely trying to reach every previous exception](https://github.com/Seldaek/monolog/blob/bfc9ebb28f97e7a24c45bdc3f0ff482e47bb0266/src/Monolog/Formatter/LineFormatter.php#L141).
It looks like that the previous attribute should be set only if the original exception (coming from a processor) is strictly different than the one re-thrown by the `QueueConsumer` at [L314](https://github.com/php-enqueue/enqueue-dev/blob/35b15fcfb5e3b34160964062e560051d7a325e17/pkg/enqueue/Consumption/QueueConsumer.php#L314))
> Avoid OutOfMemoryException

- pkg/pheanstalk/PheanstalkConsumer.php
- pkg/pheanstalk/Tests/PheanstalkConsumerTest.php
Following https://github.com/php-enqueue/enqueue-dev/pull/722
Add unit tests for acknowledge/reject/requeue.
> [pheanstalk] Add unit tests for PheanstalkConsumer

- pkg/dbal/DbalProducer.php
additional exception; avoid using Type::BOOLEAN
>  Exception on affected record !=1

- pkg/redis/RedisProducer.php
- pkg/redis/Tests/RedisProducerTest.php
Fixes #737 by converting `deliveryDelay` milliseconds to seconds in `RedisProducer::send`.
I've also included a test for the `Redis::zadd` scenario.
> [Redis] Fix messages sent with incorrect delivery delay

- pkg/async-event-dispatcher/DependencyInjection/AsyncTransformersPass.php
- pkg/async-event-dispatcher/Resources/config/services.yml
The default `php_serializer_event_transformer` will be loaded at the end in `AsyncTransformersPass` so custom event transformers can be used 
See https://github.com/php-enqueue/enqueue-dev/issues/747
> [Async Event Dispatcher]Add default to php_serializer_event_transformer

- pkg/simple-client/README.md
- pkg/simple-client/SimpleClient.php
When instantiating a SimpleClient, the internal dependencies are initialised before the LoggerInterface passed into SimpleClient is assigned. The effect of this is that dependent objects receive a NullLogger instead.
> [simple-client] Fix Logger Initialisation

- pkg/amqp-lib/AmqpConnectionFactory.php
Adding support of the new argument `channel_rpc_timeout` introduced in `php-amqplib` 2.8.2  (https://github.com/php-amqplib/php-amqplib/pull/609). This is a new optional arg in the constructor of `AMQPConnection` so it is backward compatible with `~2.8`.
> [amqp-lib] supporting channel_rpc_timeout option

- pkg/fs/FsConsumer.php
regression from this commit https://github.com/php-enqueue/fs/commit/c5199ca5bac5c661aed86d6b2f751630af42378d
config should be milliseconds like in docs stated.....$this->pollingInterval is holding milliseconds which is correct.
But usleep is using microseconds. To fix it just convert milliseconds to microseconds
> [fs] polling_interval config should be milliseconds not microseconds

- pkg/enqueue/Consumption/Context/End.php
- pkg/enqueue/Consumption/Context/PostConsume.php
- pkg/enqueue/Consumption/Context/PostMessageReceived.php
- pkg/enqueue/Consumption/Context/PreConsume.php
- pkg/enqueue/Consumption/Context/Start.php
- pkg/enqueue/Consumption/Extension/CaptureExitStatusExtension.php
- pkg/enqueue/Consumption/Extension/ExitStatusExtension.php
- pkg/enqueue/Consumption/QueueConsumer.php
- pkg/enqueue/Symfony/Client/ConsumeCommand.php
- pkg/enqueue/Symfony/Consumption/ConsumeCommand.php
- pkg/enqueue/Tests/Consumption/QueueConsumerTest.php
- pkg/enqueue/Tests/Symfony/Client/ConsumeCommandTest.php
- pkg/enqueue/Tests/Symfony/Consumption/ConsumeCommandTest.php
```php
<?php
use Enqueue\Consumption\QueueConsumer;
use Enqueue\Consumption\Extension\ExitStatusExtension;
$exitStatusExtension = new ExitStatusExtension();
$fooExtension = new class implements StartExtensionInterface {
public function onStart(Start $context) 
{
$context->interruptExecution(1); // set custom exit code
}
}
/** @var QueueConsumer $consumer **/
$consumer->consume(new ChainExtension([
$fooExtension
$exitStatusExtension
]));
exit($exitStatusExtension->getExitStatus());
```
> [consumption] Add ability to change process exit status from within queue consumer extension

- pkg/dbal/DbalConnectionFactory.php
- pkg/dbal/Tests/DbalConnectionFactoryConfigTest.php
right now user cannot declare connection options.
Reason is that always 'connection' => 'url' was set which dbal always prefers over other
connection settings. With this fix connection can be defined dbal compliant like this:
connection:
host: 'localhost'
port: '3306'
dbname: 'app'
user: 'app'
password: ''
'dsn only' works like before.
@makasim what do you think?
> [dbal]: make dbal connection config usable again

- pkg/amqp-bunny/AmqpSubscriptionConsumer.php
Bunny adapter try to catch `ClientException` when signal was triggered and exception's message is `stream_select() failed.`. However message is `stream_select() failed: Unknown error.`.
> Catch signal in Bunny adapter

- pkg/enqueue/Consumption/QueueConsumer.php
Closes #774
I finally understand how this happened and how it should be done correctly so here is the fix.
The if from #725 is not necessary. It was actually wrong anyway - the condition was always true.
I also sent the same PR to Symfony. https://github.com/symfony/symfony/pull/30327
> Fix exception loop in QueueConsumer

- pkg/amqp-tools/composer.json
Fix #783 
The enqueue/dsn must be required and not only for dev because ConnectionConfig
uses it.
> Fix amqp-tools dependency

- pkg/rdkafka/RdKafkaContext.php
Hello. I wants to support stats_cb config field first of all for my own needs but for overall system flexibility too.
> stats_cb support

- docs/transport/kafka.md
- pkg/rdkafka/RdKafkaConsumer.php
Provide additional configuration documentation for integrating with Symfony bundle
Fixes #580
> [Kafka] Set `commit_async` as true by default for Kafka, update docs

- docs/monitoring.md
- pkg/monitoring/InfluxDbStorage.php
also prevent calling database creation if Client driver does not support QueryDriverInterface.
This is a follow up from a discussion regarding #803 and a quick talk on gitter
> @steveb_gitlab I've not digged much into the issue. I guess passing a client as a part of config should work out. wdyt?
There are a couple of comments left that I should probably drop, but I've included them to make it clear for you why the code looks in a particular way (regarding `doWrite` method).  
Please tell me if there are any code style changes that you want (if you don't want `sprintf` calls maybe?) or anything else.
Fixes #803.
> [InfluxDB][Monitoring] Allow passing Client as configuration option.

- pkg/dbal/DbalConsumer.php
- pkg/dbal/Tests/DbalConsumerTest.php
- pkg/dbal/Tests/Functional/DbalConsumerTest.php
Fix #814 
I've switched to `acknowledge` first and then proceed with queueing the message again since this seems how other (Redis, RdKafka for example) work. Others seem to assume that message is automatically acknowledged when it's received.
For the same reason I'm using `acknowledge` instead of `deleteMessage` (other packages seem to work this way.
> [dbal] Fix DBAL Consumer duplicating messages when rejecting with requeue

- pkg/amqp-bunny/AmqpContext.php
- pkg/amqp-bunny/AmqpProducer.php
- pkg/amqp-bunny/Tests/AmqpProducerTest.php
As of [bunny publish method](https://github.com/jakubkulhan/bunny/blob/45702ebe4ef8d5099b5c00f0df71f4b22312203f/src/Bunny/ClientMethods.php#L1769) and [bunny content header frame](https://github.com/jakubkulhan/bunny/blob/45702ebe4ef8d5099b5c00f0df71f4b22312203f/src/Bunny/Protocol/ContentHeaderFrame.php#L120) we need to convert underscore based headers (e.g. delivery_mode) to hyphen based headers (e.g. delivery-mode) when publishing and back when recieving messages. This PR add this convertion back and forward.
Also found old closed issue that was caused by this behaviour #719
> Fix bunny producer to properly map headers to expected by bunny headers

- pkg/amqp-bunny/AmqpConnectionFactory.php
When bunny doesn't see heartbeat key in bunnyConfig it set default value to 60 seconds.
So when one set hearbeat to zero, code ignore setting this key to bunnyConfig. We should remove this check.
> Fix heartbeat configuration in bunny with 0 (off) value

- pkg/amqp-lib/AmqpSubscriptionConsumer.php
Resolves #833
Simple and straightforward fix, just initialize private property before it's used in `subscribe` method (or any other, for that matter).
> Fix un-initialized property use

- docs/transport/stomp.md
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/StompContext.php
- pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
- pkg/stomp/Tests/StompConnectionFactoryTest.php
- pkg/stomp/Tests/StompContextTest.php
Add support for using the /topic prefix instead of /exchange. RabbitMQ needs the /exchange prefix for publishing on an exchange, while ActiveMQ needs the /topic prefix for publishing on a topic
>  Add support for using the /topic prefix instead of /exchange.

- pkg/sns/SnsMessage.php
- pkg/sns/SnsProducer.php
- pkg/sns/Tests/SnsProducerTest.php
Currently the message and producer do not allow for using Sns message attributes.
Message attributes are provided to the AwsSnsClient as described [here](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-sns-2010-03-31.html#publish).
These are needed to use the [Message Filtering](https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html) feature.
> Allow setting SNS message attributes, other fields

- pkg/enqueue/Symfony/DependencyInjection/TransportFactory.php
The command docs say the default is `100 ms` but that's not true, it's `10000 ms` by default.
I also wonder what is correct, I mean, in what world do you want a worker to wait 10 seconds between jobs? Maybe 100 ms should've been the right value?
> Fixed docs

- pkg/rdkafka/RdKafkaConsumer.php
Recent versions may no longer return error message when reaching end of partition
(`RD_KAFKA_RESP_ERR__PARTITION_EOF` - due to change in `enable.partition.eof`).
This is especially true for librdkafka >=1.0.0.
see https://github.com/arnaud-lb/php-rdkafka/issues/220#issuecomment-491162230
> [Kafka] Fix consumption errors in kafka against recent versions in librdkafka/phprdkafka

- pkg/monitoring/InfluxDbStorage.php
`topic` and `command` are important to know what messages exactly are causing any failures, if anything wrong happens. `queue` is the same for all topics with default configuration.
The code is same as with emitted messages.
Tested with real use-case inside symfony project.
> Send topic and command for consumed messages

- pkg/sqs/SqsConsumer.php
- pkg/sqs/SqsMessage.php
- pkg/sqs/Tests/SqsConsumerTest.php
This follows discussion started here: https://github.com/php-enqueue/enqueue-dev/commit/257fdb5fbcb95d141ced3de2fc0d1dfd2a53fb3d#r33577211
> [SQS] Requeue with a visibility timeout

- pkg/enqueue/Consumption/QueueConsumerInterface.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/841
> Fix bindCallback method will require new arg deprecation notice

- composer.json
See https://getcomposer.org/doc/04-schema.md#prefer-stable
This PR causes development & CI to use stable versions of dependencies. Noticed this when `v4.3.0-BETA2` Symfony dependencies were being installed locally.
Should have no real effect on library use, since `prefer-stable` is root-only setting for composer, while preventing possibly broken build from crashing CI for example.
> Prefer stable dependencies for development

- docs/.gitignore
- docs/Gemfile
- docs/_config.yml
- docs/_includes/nav.html
- docs/index.md
> Switch documentation to github pages

- README.md
- bin/subtree-split
- docs/_config.yml
@makasim This should allow hosting github pages under "organization" without enqueue-dev suffix (https://php-enqueue.github.io/).
I didn't do full lookup if repository split works since I have access to organization, but it should work.
> Use organization repository for doc hosting

- .editorconfig
see https://editorconfig.org/
This should provide common settings. Most IDE's (PhpStorm, VS Code) support editorconfig declaration either directly or via a plugin.
> Add editor config settings for IDE's that support it

- docs/bundle/async_commands.md
- docs/bundle/async_events.md
- docs/bundle/cli_commands.md
- docs/bundle/config_reference.md
- docs/bundle/consumption_extension.md
- docs/bundle/debugging.md
- docs/bundle/functional_testing.md
- docs/bundle/index.md
- docs/bundle/job_queue.md
- docs/bundle/message_processor.md
- docs/bundle/message_producer.md
- docs/bundle/production_settings.md
- docs/bundle/quick_tour.md
- docs/index.md
- docs/quick_tour.md
Actually there is a lot of documentation for Symfony but it's not easy to navigate through the pages as the links always get you back to the general doc instead of a Symfony homepage
> Better Symfony doc nav

- docs/bundle/quick_tour.md
According to comments in #884.
> [Bundle] Expand quick tour for Symfony Bundle

- docs/concepts.md
- docs/index.md
Minor adjustments as part of ongoing issue #838
> Move "key concepts" to second position in menu. Fix typos.

- pkg/amqp-lib/Tests/AmqpProducerTest.php
- pkg/dbal/DbalConsumer.php
- pkg/dbal/DbalMessage.php
- pkg/dbal/Tests/DbalConsumerTest.php
- pkg/dbal/Tests/DbalSubscriptionConsumerTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClearIdentityMapExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrinePingConnectionExtensionTest.php
- pkg/enqueue/Client/Message.php
- pkg/enqueue/Consumption/Context/MessageResult.php
- pkg/enqueue/Tests/Client/DelegateProcessorTest.php
- pkg/enqueue/Tests/Client/Extension/PrepareBodyExtensionTest.php
- pkg/enqueue/Tests/Consumption/FallbackSubscriptionConsumerTest.php
- pkg/job-queue/Tests/CalculateRootJobStatusProcessorTest.php
- pkg/job-queue/Tests/CalculateRootJobStatusServiceTest.php
- pkg/job-queue/Tests/DependentJobProcessorTest.php
- pkg/job-queue/Tests/DependentJobServiceTest.php
- pkg/job-queue/Tests/Doctrine/JobStorageTest.php
- pkg/job-queue/Tests/JobProcessorTest.php
- pkg/job-queue/Tests/JobRunnerTest.php
- pkg/mongodb/Tests/MongodbConsumerTest.php
- pkg/mongodb/Tests/MongodbSubscriptionConsumerTest.php
- pkg/redis/Tests/RedisSubscriptionConsumerTest.php
- pkg/redis/Tests/Spec/JsonSerializerTest.php
- pkg/sns/Tests/SnsProducerTest.php
- pkg/sqs/Tests/SqsProducerTest.php
- pkg/wamp/Tests/Spec/JsonSerializerTest.php
This PR fixes all outstanding code style violations in all PHP files in project.
> Fix Code Style in all files

- pkg/rdkafka/RdKafkaConsumer.php
A simpler part of #843, adds just the consumption part. This makes
headers accessible in the consumer in case another application makes
use of those, be it PHP or not.
> Allow reading headers from Kafka Message headers

- pkg/dbal/DbalContext.php
We need to cast int when dsn query returned the string value
> Cast int for redelivery_delay and polling_interval

- pkg/sqs/SqsConsumer.php
- pkg/sqs/SqsMessage.php
- pkg/sqs/Tests/SqsConsumerTest.php
- pkg/sqs/Tests/SqsMessageTest.php
Allow deserializing all messages attributes, which we can use for logging and debugging.
> deserialize sqs message attributes

- composer.json
- docs/contribution.md
This allows for forks in composer requiring whole package (enqueue) to
work properly.
Also add code style commands as composer scripts for ease of use.
This allows calling for example `composer run cs-fix some-file.php`.
> Add composer runnable scripts for PHPStan & PHP-CS

- pkg/snsqs/SnsQsProducer.php
- pkg/snsqs/Tests/SnsQsProducerTest.php
I'm trying to use SNSQS in my infrastructure with Symfony Client. 
I found out that `\Enqueue\Client\Driver\GenericDriver` calls `setDeliveryDelay` in method `sendToProcessor` when the message is delayed. 
SNSQS should support that as the `commands` sent from the Client should support it (it's going through SQS). 
I fixed the bug and test the producer.
> [SNSQS] Fix issue with delay

- pkg/sns/SnsProducer.php
- pkg/sns/Tests/SnsProducerTest.php
I found out that SNS producer is not throwing an exception which causes another issue - method response is not `Producer`. 
I fixed this and covered with tests. 
PS:
Probably, this was done to make it work with #909 but it's not. Now both of the functionalities should work as they should.
> [SNS] Fix: Missing throw issue

- pkg/dbal/DbalConsumerHelperTrait.php
Doctrine DBAL version 2.6 does not have ParameterType class.
and the library supports version 2.6 of Doctrine DBAL.
Hope it will be merge soon.
Thanks.
> DBAL Change ParameterType class to Type class

- pkg/enqueue-bundle/Consumption/Extension/DoctrineClearIdentityMapExtension.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClearIdentityMapExtensionTest.php
We only use the method `getManagers()` which comes from this interface, and not the RegistryInterface from Sf's doctrine bridge. So it makes sense to allow passing implementations of parent interfaces.
This will also allow us to use this class with Doctrine ODM.
> [DoctrineClearIdentityMapExtension] allow instances of ManagerRegistry

- docs/bundle/config_reference.md
- docs/consumption/extensions.md
- pkg/enqueue-bundle/Consumption/Extension/ResetServicesExtension.php
- pkg/enqueue-bundle/DependencyInjection/Configuration.php
- pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/ResetServicesExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php
- pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
Reset services tagged by "kernel.reset".
> Add an extension to reset services

- pkg/rdkafka/RdKafkaContext.php
- pkg/rdkafka/Tests/RdKafkaContextTest.php
Hi, introduce a `rdKafkaConsumers` collection to avoid the creation of multiple consumers for the same queue. This PR solve the issue #894 and #893  (I've tried the solution on this [project](https://github.com/marcoreni/enqueue-kafka-894-repro) and it works)
> Kafka singleton consumer

- pkg/rdkafka/RdKafkaContext.php
- pkg/rdkafka/RdKafkaProducer.php
- pkg/rdkafka/Tests/RdKafkaProducerTest.php
- pkg/rdkafka/composer.json
This bumps the dependency on rdkafka extension from version `3.0.3` to `3.1.0`.
> Add header support for kafka

- pkg/enqueue/Symfony/Client/DependencyInjection/BuildCommandSubscriberRoutesPass.php
- pkg/enqueue/Symfony/Client/DependencyInjection/BuildTopicSubscriberRoutesPass.php
Fix empty class for autowired services at least in Symfony 3.4 (Not tested for other versions).
More information in the related issue #957.
> Fix empty class for autowired services (Fix #957)

- pkg/enqueue/Symfony/Client/ProduceCommand.php
- pkg/enqueue/Tests/Symfony/Client/ProduceCommandTest.php
- pkg/enqueue/Tests/Symfony/Client/SimpleProduceCommandTest.php
> Add header support for Symfony's produce command

- pkg/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php
- pkg/enqueue/Tests/DoctrineConnectionFactoryFactoryTest.php
Hey guys,
i adjusted the code from #985 and added a test for this class.
#SymfonyHackday
> Fix Incompatibility for doctrine

- pkg/gearman/GearmanConsumer.php
When looping the worker->work() call, the receive method will fetch all messages in the queue, but only return the last one.
The fix will return only one message.
> Gearman Consumer receive should only fetch one message

- pkg/snsqs/Tests/SnsQsProducerTest.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
- pkg/sqs/Tests/SqsConnectionFactoryTest.php
This PR add support for AWS profiles, it reponds to issue https://github.com/php-enqueue/enqueue-dev/issues/1007.
Closes: #1007
> SQS Transport - Add support for AWS profiles.

- pkg/amqp-lib/AmqpContext.php
Fixes:
```
Return value of Enqueue\AmqpLib\AmqpContext::declareQueue() must be of the type int, null returned
```
> fixes #1003

- pkg/rdkafka/RdKafkaConsumer.php
Catch the Kafka `Local: Broker transport failure` (error -195) error when consuming, this happens sometimes when consuming messages. When we restart the consumer everything is just OK.
Settings for connection with Kafka:
```
enqueue:
kafka:
transport:
global:
group.id: XXX
metadata.broker.list: XXX
enable.auto.offset.store: 'false'
socket.keepalive.enable: 'true'
topic.metadata.refresh.interval.ms: '30000'
```
@makasim
> Catch consume error "Local: Broker transport failure" and continue consume

- pkg/snsqs/Tests/SnsQsProducerTest.php
- pkg/sqs/SqsConsumer.php
- pkg/sqs/SqsMessage.php
- pkg/sqs/Tests/Functional/SqsCommonUseCasesTest.php
- pkg/sqs/Tests/SqsConsumerTest.php
Hi,
I saw that we are not allowing user to access the messageId of a sqs message.
following the issue #837 i have added the messageId in the convertMessage method.
> [SQS] add messageId to the sqsMessage

- phpunit.xml.dist
- pkg/amqp-bunny/phpunit.xml.dist
- pkg/amqp-ext/phpunit.xml.dist
- pkg/amqp-lib/phpunit.xml.dist
- pkg/async-event-dispatcher/phpunit.xml.dist
- pkg/dbal/phpunit.xml.dist
- pkg/dsn/phpunit.xml.dist
- pkg/enqueue-bundle/phpunit.xml.dist
- pkg/enqueue/phpunit.xml.dist
- pkg/fs/phpunit.xml.dist
- pkg/gearman/phpunit.xml.dist
- pkg/gps/phpunit.xml.dist
- pkg/job-queue/phpunit.xml.dist
- pkg/mongodb/phpunit.xml.dist
- pkg/monitoring/phpunit.xml.dist
- pkg/null/phpunit.xml.dist
- pkg/pheanstalk/phpunit.xml.dist
- pkg/rdkafka/phpunit.xml.dist
- pkg/redis/phpunit.xml.dist
- pkg/simple-client/phpunit.xml.dist
- pkg/sns/phpunit.xml.dist
- pkg/snsqs/phpunit.xml.dist
- pkg/sqs/phpunit.xml.dist
- pkg/stomp/phpunit.xml.dist
- pkg/wamp/phpunit.xml.dist
also: 
Remove parameters set to php unit defaults.
> Add schema declaration to phpunit files

- pkg/dbal/DbalConnectionFactory.php
- pkg/dbal/Tests/DbalConnectionFactoryTest.php
Hi,
when switching from `amqp+lib` to `sqlite3` transport, we were not able to setup DSNs with absolute paths. It seems that `parse_url()` only allows more than 2 slashes for `file:` scheme and fails for other schemes (see [Notes in the documentation](https://www.php.net/manual/en/function.parse-url.php)). SQLite however happily uses [3 and more slashes for DSNs](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#connecting-using-a-url).
This PR proposes a special handling for `sqlite:` scheme and fixes #780. Relevant changes are lines 100-103, the rest is php-cs-fixer.
> fix: allow absolute paths for sqlite transport

- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/Tests/Functional/StompConnectionFactoryTest.php
- pkg/stomp/Tests/StompConnectionFactoryConfigTest.php
- pkg/stomp/Tests/StompConnectionFactoryTest.php
- pkg/test/RabbitmqStompExtension.php
possibility to configurate heartbeat
see #968
> STOMP. add additional configuration

- pkg/pheanstalk/PheanstalkProducer.php
- pkg/pheanstalk/Tests/PheanstalkProducerTest.php
I could not take advantage of the `MultiplierRetryStrategy` built in to the Symfony Messenger component, because the Pheanstalk producer did not fully implement the `setDeliveryDelay` method (see also #821). Even though I only needed the delay, I went ahead and fully implemented the priority and time to live functionality of the `Producer` interface as well.
The code changes in the PR essentially do three things:
1.  ensures that “delivery delay” and “time to live” are set as milliseconds on the producer but passed to the transport as seconds; 
2. ensures that the respective message values are used when priority, delay or TTL is null; and
3. ensures that any producer values do not persist for more than one send.
Each of these points has test coverage.
> Implement DeliveryDelay, Priority and TimeToLive in PheanstalkProducer

- pkg/redis/RedisConnectionFactory.php
if used in dsn query, it returns a string, so it should be cast to int here
> Changed: cast redelivery_delay to int

- pkg/rdkafka/RdKafkaConsumer.php
Prevent the vscode intelephense error : "Undefined method 'getPartition'."
> chore: add typehint to RdKafkaConsumer#getQueue

- docs/client/supported_brokers.md
- docs/transport/index.md
Added several missing ones, corrected Redis/FS's missing features, and added a Heartbeat column.
Also reordered them to match the navigation's alphabetical order (in a separate commit so the first's diff is clearer).
> Docs: update Supported Brokers

- pkg/async-command/DependencyInjection/AsyncCommandExtension.php
addArgument add only one argument at a time to the construtor, right now the timeout configured by the user is never applied and it's always the default (60) value, this fixes it.
> [async-command] Fix service definition to apply the timeout

- .travis.yml
- composer.json
- docker-compose.yml
- pkg/rdkafka/RdKafkaConnectionFactory.php
- pkg/rdkafka/RdKafkaContext.php
- pkg/rdkafka/RdKafkaProducer.php
- pkg/rdkafka/Tests/Spec/RdKafkaSendToAndReceiveFromTopicTest.php
- pkg/rdkafka/composer.json
@see https://github.com/arnaud-lb/php-rdkafka/releases/tag/4.0.0
Since `poll` no longer gets called on destruct/shutdown, we should provide error handling (#749).
I'm marking this as draft PR since otherwise we might have people losing messages when PHP process shuts down before message is acknowledged by Kafka broker.
> Compatibility with Phprdkafka 4.0

- pkg/enqueue/Tests/Client/Driver/RabbitMqStompDriverTest.php
- pkg/enqueue/Tests/Client/Driver/StompDriverTest.php
- pkg/stomp/ExtensionType.php
- pkg/stomp/StompConnectionFactory.php
- pkg/stomp/StompConsumer.php
- pkg/stomp/StompContext.php
- pkg/stomp/StompDestination.php
- pkg/stomp/Tests/StompConsumerTest.php
- pkg/stomp/Tests/StompContextTest.php
- pkg/stomp/Tests/StompDestinationTest.php
- pkg/stomp/Tests/StompProducerTest.php
Hey @makasim! :wave:
I've managed to put together a first draft for supporting ActiveMQ Artemis using the Enqueue STOMP driver. I have this working locally and I've done my best to stick to your code style, giving in to the odd improvement.
The biggest change I've made is to plumb the notion of broker extensions a bit further into the hierarchy of objects. I noticed in quite a few places, RabbitMQ preferences are hard-coded because there wasn't any way to check which set of extensions are desired for the connection. I'll make further notes on the code in the PR to help you scan through things.
Let me know what you think and note any changes or improvements you're after. I have not added tests as I am hoping to get help from you on that if it's something you want done.
Closes: …
> Add first pass for Apache ActiveMQ Artemis support

- pkg/stomp/StompProducer.php
This is to accommodate any situations where `0` is passed via configuration or even defaults from other layers (in my case, laravel).
> Allow false-y values for unsupported options

- docker/Dockerfile
So `php-rdkafka:4.x` only supports `librdkafka:0.11.6` and up. I would strongly suggest though, that you force your users to use `librdkafka:1.x` and up. If you guys agree, i can create a PR to enforce this and adjust this one to use at least `librdkafka:1.0`
FYI: `php-rdkafka:5.0` will drop support for anything lower than `librdkafka:1.2`
> use supported librdkafka version of ext

- pkg/rdkafka/RdKafkaProducer.php
- pkg/rdkafka/Tests/RdKafkaProducerTest.php
Should fix #749, calling `poll(0)` is non-blocking and poses minimal overhead. This way callbacks can be triggered, which is important to receive errors, delivery reports, etc. when producing a message.
> [rdkafka] add non-blocking poll call to serve cb's

- composer.json
- docs/transport/dbal.md
- pkg/dbal/ManagerRegistryConnectionFactory.php
- pkg/dbal/Tests/ManagerRegistryConnectionFactoryTest.php
- pkg/dbal/composer.json
- pkg/enqueue-bundle/Consumption/Extension/DoctrineClearIdentityMapExtension.php
- pkg/enqueue-bundle/Consumption/Extension/DoctrineClosedEntityManagerExtension.php
- pkg/enqueue-bundle/Consumption/Extension/DoctrinePingConnectionExtension.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClearIdentityMapExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClosedEntityManagerExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrinePingConnectionExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/ResetServicesExtensionTest.php
- pkg/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php
- pkg/enqueue/Tests/DoctrineConnectionFactoryFactoryTest.php
- pkg/job-queue/Doctrine/JobStorage.php
- pkg/job-queue/Tests/Doctrine/JobStorageTest.php
continuing for the suggested pr #1089 of this issue #1085
> fixing issue #1085

- composer.json
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClearIdentityMapExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrineClosedEntityManagerExtensionTest.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/DoctrinePingConnectionExtensionTest.php
- pkg/enqueue/Doctrine/DoctrineConnectionFactoryFactory.php
- pkg/enqueue/Tests/DoctrineConnectionFactoryFactoryTest.php
Fix #1085 - Fix to be compatible with doctrine v3 . Since Doctrine v3, seems some changes with doctrine/common
> Fix DoctrineConnectionFactoryFactory due to doctrine/common changes

- pkg/monitoring/ConsumerMonitoringExtension.php
- pkg/monitoring/composer.json
A correct copy of https://github.com/php-enqueue/monitoring/pull/2
> Ramsey dependency removed in favor to \Enqueue\Util\UUID::generate

- pkg/enqueue/Consumption/Context/ProcessorException.php
- pkg/enqueue/Consumption/QueueConsumer.php
This fixes the issue with unhandled Errors described in #1113
tbd. if this might be considered breaking backward compatibility or if I missed any important place.
Actually it should not, since \Exception extends from \Throwable. But feel free to comment & object.
> [fix] queue consumption: catch throwable for processing errors

- pkg/rdkafka/composer.json
ext-rdkafka v5.0 is out! As per the [release notes](https://github.com/arnaud-lb/php-rdkafka/releases/tag/5.0.0), there is no impact on enqueue.
> Allow ext-rdkafka 5

- pkg/stomp/StompConsumer.php
I noticed some errors earlier when this line gets hit for exceptions.  I believe the issue is the `null` instead of a `0` to match the default parameter.
> Fix - Bad parameter for exception

- .github/workflows/ci.yml
I noticed there are some suspicious jobs, like `unit=, functional=, ...` — not `true` or `false` => not running anything useful.
Also added a note about the php version for the functional and rdkafka tests — doesn't change the outcome but will help later when adapting the suite to php 8.
> Fix the build matrix

- pkg/gps/GpsMessage.php
- pkg/gps/Tests/GpsMessageTest.php
> [gps] Add support for consuming message from external publisher in non-standard format

- pkg/job-queue/composer.json
Try to use doctrine/orm 2.8 with job queue, this is the last step to php 8 support.
> Try to change doctrine/orm version for supporting 2.8 (PHP 8 support).

- pkg/snsqs/SnsQsConsumer.php
It's not currently possible to set the visibility timeout or max number of messages on the SnsQsConsumer even though they are available on the SqsConsumer, I thought it would be helpful to expose those so added this PR.
> Add SqsConsumer methods to SnsQsConsumer

- pkg/dbal/DbalContext.php
- pkg/dbal/DbalSubscriptionConsumer.php
- pkg/dbal/Tests/DbalContextTest.php
I am facing an issue with the situation, that I have a few JobWorker running and my DB doesn't like that many requests. Without the change, I am getting 50 Requests in 10 Seconds with 1 JobWorker. Because of this, I am getting many "MySQL Server has gone away" messages.
> add subscription_interval as config for dbal subscription consumer

- pkg/dbal/DbalProducer.php
Fixes incorrect calculations that may result in float instead of int:
`SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"1619173911.5\" at /data/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:102, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"1619173911.5\" at /data/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"1619173911.5\" at /data/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)`
> Fix dbal delivery delay to always keep integer value

- pkg/dbal/DbalConsumer.php
During rejection with requeue there is possibility for losing message. 
The scenario may happen, if after acknowledge we will lose connection. 
In that case, message will not be redelivered and original message will be lost. 
Given solution performs redelivery first and then perform the acknowledge. 
In the scenario with losing the connection in between, the message will be delivered twice instead of being lost. 
This work in "at least once delivery" manner, just like RabbitMQ.
> Perform at least once delivery when rejecting with requeue

- pkg/job-queue/CalculateRootJobStatusProcessor.php
- pkg/job-queue/CalculateRootJobStatusService.php
- pkg/job-queue/Doctrine/JobStorage.php
Before determine Root Job Status Doctrine cache for Job entity must be cleared, otherwise if this root job was processed in previous request by the same enqueue, then it will falsely return old status, which will cause infinite running root jobs
> Changed: Clear Doctrine cache before calculate Root Job Status

- pkg/enqueue-bundle/Consumption/Extension/ResetServicesExtension.php
- pkg/enqueue-bundle/Tests/Unit/Consumption/Extension/ResetServicesExtensionTest.php
Resolves https://github.com/php-enqueue/enqueue-dev/issues/1156
Reset the services after message is received, so that logs are flushed without having to wait for a new message
> ResetServicesExtension to run _after_ message received

- .github/workflows/ci.yml
- composer.json
- docker-compose.yml
- docker/Dockerfile
- pkg/enqueue-bundle/composer.json
- pkg/monitoring/composer.json
- pkg/snsqs/SnsQsConsumer.php
- pkg/snsqs/Tests/SnsQsConsumerTest.php
- pkg/wamp/composer.json
In snsqs usage scenario you still get non-SNS messages when you resend a message for retrying.
Additional unrelated fixes to make it right:
- Fixed functional test runner in CI to apply different PHP versions rather than the same one;
- Dropped PHP 7.3 and added 7.4 to the functional test matrix;
- Bumped dependencies to versions compatible with PHP 8.0;
- Bump react libs to fix wamp hanging on PHP 8.
> Fix snsqs non-SNS SQS message headers

- pkg/dbal/DbalContext.php
Background is a shopware 6.4 installation. We have 3.4 million entries in the mysql table enqueue.
A query like: DELETE FROM enqueue WHERE delivery_id = '1ea18942-283b-4cfd-a24a-1bf9917a9d0f'
takes 20-60 seconds. CPU load is by 100%. So this provides a race condition as the enqueue-table is growing fast and deleting entries is very slow.
Creating directly in mysql an index on delivery_id solves the problem. Queries are again done in milliseconds.
> #1190 add index on delivery_id to prevent slow queries

- pkg/sns/SnsContext.php
- pkg/snsqs/SnsQsContext.php
> Add setTopicArn methods to SnsContext and SnsQsContext

- pkg/sns/SnsConnectionFactory.php
- pkg/sns/Tests/SnsConnectionFactoryConfigTest.php
- pkg/sns/Tests/SnsConnectionFactoryTest.php
- pkg/sqs/SqsConnectionFactory.php
- pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php
- pkg/sqs/Tests/SqsConnectionFactoryTest.php
This changes allow to set in the AWS Sdk client the http configurations:
https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html#config-http
This will make possible to define custom `connect_timeout` and
`timeout` to fail fast when the network is not relaible.
Reported on https://github.com/php-enqueue/enqueue-dev/issues/1213
> feat(snsqs): allow client http configuration for sns and sqs

- composer.json
`ext-rdkafka` v6.0 is available.
Allow its usage in this library.
According to the [release note](https://github.com/arnaud-lb/php-rdkafka/releases/tag/6.0.0), there's no BC breaks.
> Allow ext-rdkafka 6 usage

- composer.json
A year has passed since https://github.com/richardfullmer/php-rabbitmq-management-api/pull/11 — time to move on and stop using the fork as a custom repo.﻿
This will make all the builds quicker, race-condition free, and avoid the weirdness of using a source repo in a widely used package.
Included into https://github.com/php-enqueue/enqueue-dev/pull/1239, might as well just merge that one.
> Replace rabbitmq-management-api with a packagist source

- pkg/stomp/.github/workflows/ci.yml
- pkg/stomp/composer.json
Basically this just does what @andrewmy has already done in this PR for the stomp package, details here: https://github.com/php-enqueue/enqueue-dev/pull/1238/commits/d1a2239b58286ca83ab0ca90f407fa9123ce9266
This is done for all the same reasons to "_make builds quicker, race-condition free, and avoid the weirdness of using a source repo in a widely used package._"
Also fixed small typo that would prevent github actions from working if that is ever needed in future.
> Replace rabbitmq-management-api with a packagist source and fixed small github actions typo

- pkg/amqp-bunny/AmqpSubscriptionConsumer.php
Fixes 8.1 compatibility
```
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/bunny/bunny/src/Bunny/ClientMethods.php on line 1638
```
> Ensure pass consumer tag as string to bunny amqp

- pkg/enqueue/Symfony/DependencyInjection/TransportFactory.php
- pkg/enqueue/Tests/Symfony/DependencyInjection/TransportFactoryTest.php
The symfony [config reference](https://github.com/php-enqueue/enqueue-dev/blob/0b7bd9cfbc484cf3625a01baa5b3f5c711a11826/docs/bundle/config_reference.md) states as default
```yaml
transport:
connection_factory_class: ~
factory_service: ~
```
where ~ is null, but setting these values to null, throws an error, as the actual TransportFactory uses array_key_exists() which doesn't care if the value is null or not and in case sets e.g. the FactoryService to null which isn't supported
This change makes use of isset() and the Null Coalescing Operator which does also look up if the value is null
> Symfony config allow null

- pkg/sqs/SqsProducer.php
Missing parenthesis here would allow the delay to be a fraction of a second and cause an error if the delay provided was not a multiple of 1000.
> fix: parenthesis missing allowed invalid delays

- pkg/amqp-lib/AmqpContext.php
- pkg/amqp-lib/AmqpSubscriptionConsumer.php
- pkg/amqp-lib/Tests/AmqpConsumerTest.php
- pkg/amqp-lib/composer.json
Also, require more recent php-amqplib version.
> [amqp-lib] Replace amqp-lib deprecated public property with getters

- pkg/sns/Tests/SnsClientTest.php
- pkg/sqs/Tests/SqsClientTest.php
It looks like in recent versions the AWS SDK started enforcing parameter types, breaking our CI.
> `InvalidArgumentException: Invalid configuration value provided for "token". Expected Aws\Token\TokenInterface|Aws\CacheInterface|array|bool|callable, but got string(0) ""`
When passing `false`, it still breaks:
> `InvalidArgumentException: Token must be an instance of Aws\Token\TokenInterface, an associative array that contains "token" and an optional "expires" key-value pairs, a token provider function, or false.`
So let's just skip it in tests.
> Fix AWS SDK token parameter

- composer.json
- pkg/sns/SnsClient.php
- pkg/sns/SnsContext.php
- pkg/sns/Tests/Spec/SnsContextTest.php
- pkg/snsqs/SnsQsContext.php
- pkg/snsqs/Tests/Spec/SnsQsContextTest.php
Not sure yet whether to add the support for attributes to `subscribe` as well, out of scope I guess.
> Add setting subscription attributes to Sns and SnsQs

- pkg/mongodb/MongodbContext.php
Hey there 👋
In Printify we are utilizing this library quite heavily.
Recently we had an incident with the super high CPU and I/O usage in MongoDB.
With multiple queues and thousands of messages per queue, MongoDB is doing a full collection scan.
The combined index solves that.
> MongoDB - Add combined index

- pkg/job-queue/Doctrine/mapping/Job.orm.xml
This should be a fix for #1293
> Replaced `json_array` with `json` due to Doctrine Dbal 3.0

- pkg/dbal/composer.json
Currently on Symfony 6.2 there is an issue related to the doctrine/persistence. Symfony recommends to use the doctrine/persistence in the latest version 3.1 to use of lazy ghost objects.
It's also related to the ecotone that is using enqueue: https://github.com/ecotoneframework/ecotone-dev/issues/111
@makasim
> Allow doctrine/persistence 3.1 version

- pkg/redis/PhpRedis.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
Since v5 PHPRedis supports providing a host scheme, so you can configure it to use tls
> Add support for rediss and phpredis

- pkg/redis/RedisConsumer.php
- pkg/redis/Tests/RedisConnectionFactoryConfigTest.php
- pkg/redis/Tests/RedisConsumerTest.php
This change will allow to use `$message->getAttempts()` when `true === $message->isRedelivered()` to find how many times this message has been requeue/redelivered. Such information is useful to decide if the message should be `requeue` to retry again later or `rejected` to be completely removed from the queue in case of error.
Something similar was asked on https://github.com/php-enqueue/enqueue-dev/issues/940 but the suggestion on https://github.com/php-enqueue/enqueue-dev/issues/940#issuecomment-1017173629 is about adding another header with a similar purpose than `attempts`. 
On `\Enqueue\Redis\RedisConsumerHelperTrait::processResult()` we already increment `attempts` header, so if we don't reset it when the message is requeue we will have the accurate information about how many times …
> fix: do not reset attemps header when message is requeue

- pkg/enqueue/Client/CommandSubscriberInterface.php
HI @makasim,
The `CommandSubscriberInterface::getSubscribedCommand` is currently annotated with `string|array` return type.
Static analysis tool allows to provide a more precise return type.
This PR allow PHPStan and Psalm users to have to proper static analysis of the return type when implementing the interface.
I based the array type on the current phpdoc, talking about 
```
* [
*   'command' => 'aSubscribedCommand',
*   'processor' => 'aProcessorName',
*   'queue' => 'a_client_queue_name',
*   'prefix_queue' => true,
*   'exclusive' => true,
* ]
```
> [ENQUEUE] Precise phpdoc for static analysis

- pkg/enqueue/Client/PreSendCommandExtensionInterface.php
- pkg/enqueue/Client/PreSendEventExtensionInterface.php
- pkg/enqueue/Client/ProducerInterface.php
HI @makasim 
When calling `sendCommand` it's useful to know the method can throws Exception, it's currently the case for the proposed implementations.
Thanks to PHPStorm or static analysis tool like PHPStan, it will help people try/catching the calls and avoid error in production.
> [ENQUEUE] Add missing throws tag to interfaces

- pkg/rdkafka/RdKafkaProducer.php
Looking at the rdkafka docs (https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/rdkafka.flush.html) flush returns an integer instead of void in Producer class. This PR sets the same return type.
> Set return type to flush function in RdkafkaProducer to be compatible to php-rdkafka

- .github/workflows/ci.yml
- docker/Dockerfile
- pkg/enqueue/Symfony/Client/ConsumeCommand.php
- pkg/enqueue/Symfony/Client/ProduceCommand.php
- pkg/enqueue/Symfony/Client/RoutesCommand.php
- pkg/enqueue/Symfony/Client/SetupBrokerCommand.php
- pkg/enqueue/Symfony/Consumption/ConfigurableConsumeCommand.php
- pkg/enqueue/Symfony/Consumption/ConsumeCommand.php
- pkg/sns/Tests/SnsClientTest.php
- pkg/sqs/Tests/SqsClientTest.php
Fixes the following deprecations:
```json
{
"message": "Since symfony/console 6.1: Relying on the static property \"$defaultName\" for setting a command name is deprecated. Add the \"Symfony\\Component\\Console\\Attribute\\AsCommand\" attribute to the \"Enqueue\\Symfony\\Consumption\\ConfigurableConsumeCommand\" class instead.",
"count": 1
},
{
"message": "Since symfony/console 6.1: Relying on the static property \"$defaultName\" for setting a command name is deprecated. Add the \"Symfony\\Component\\Console\\Attribute\\AsCommand\" attribute to the \"Enqueue\\Symfony\\Client\\ConsumeCommand\" class instead.",
"count": 1
},
{
"message": "Since symfony/console 6.1: Relying on the static property \"$defaultName\" for setting a command name is deprecated. Add the …
```
> Use `#[AsCommand]` attribute on commands

- bin/changelog
- bin/dev
- bin/test.sh
- composer.json
- docker-compose.yml
- docker/bin/test.sh
- docs/contribution.md
- docs/transport/gps.md
- phpunit.xml.dist
- pkg/amqp-ext/Tests/Functional/AmqpCommonUseCasesTest.php
- pkg/gps/GpsMessage.php
- pkg/gps/GpsProducer.php
- pkg/gps/Tests/GpsMessageTest.php
- pkg/gps/Tests/GpsProducerTest.php
- pkg/sns/composer.json
- pkg/snsqs/Tests/Spec/SnsQsSendToTopicAndReceiveNoWaitFromQueueTest.php
- pkg/sqs/composer.json
Allow to send PubSub attributes
> feat(GPS): allow send attributes in Google PubSub message.

- pkg/gps/GpsMessage.php
- pkg/gps/GpsProducer.php
- pkg/gps/Tests/GpsMessageTest.php
- pkg/gps/Tests/GpsProducerTest.php
I found that i was go in wrong direction. 
The GPS attributes are the Interop Message headers. 
I revert to use the `headers` and remove the `attributes`
> GPS: revert the attributes and use the headers instead.

- pkg/enqueue/Symfony/Client/DependencyInjection/ClientFactory.php
Due to this, upgrading from SF 6.4.7 to more recent versions is impossible.
Output from the `cache:clear` after upgrade:
```
Executing script cache:clear [KO]
[KO]
Script cache:clear returned with error code 255
!!  TypeError {#5946
!!    #message: "Symfony\Component\Config\Definition\Builder\NodeDefinition::end(): Return value must be of type Symfony\Component\Config\Definition\Builder\NodeParentInterface, null returned"
!!    #code: 0
!!    #file: "./vendor/symfony/config/Definition/Builder/NodeDefinition.php"
!!    #line: 98
!!    trace: {
!!      ./vendor/symfony/config/Definition/Builder/NodeDefinition.php:98 { …}
!!      ./vendor/enqueue/enqueue/Symfony/Client/DependencyInjection/ClientFactory.php:82 { …}
!!      ./vendor/enqueue/enqueue-bundle/DependencyInjection/Configuration.php:4 …
```
> Drop useless call to end method
