php-enqueue/enqueue-dev

pkg/amqp-ext/AmqpConsumer.php, pkg/amqp-ext/Tests/Functional/AmqpCommonUseCasesTest.php
- Internally it has to be converted to seconds.
=> [bug][amqp-ext] Receive timeout parameter is miliseconds

.travis.yml, docker-compose.yml
fixes https://github.com/php-enqueue/enqueue-dev/issues/17, https://github.com/php-enqueue/enqueue-dev/issues/16
=> [travis] Run test with different Symfony versions. 2.8, 3.0

docs/client/rpc_call.md, docs/index.md, pkg/amqp-ext/Client/AmqpDriver.php, pkg/amqp-ext/Tests/Client/AmqpDriverTest.php, pkg/amqp-ext/Tests/Client/RabbitMqDriverTest.php, pkg/enqueue-bundle/Resources/config/client.yml, pkg/enqueue-bundle/Resources/config/services.yml, pkg/enqueue-bundle/Tests/Functional/RpcClientTest.php, pkg/enqueue/Client/Message.php, pkg/enqueue/Client/NullDriver.php, pkg/enqueue/Client/RpcClient.php, pkg/enqueue/Consumption/Extension/ReplyExtension.php, pkg/enqueue/Rpc/Promise.php, pkg/enqueue/Rpc/RpcClient.php, pkg/enqueue/Rpc/TimeoutException.php, pkg/enqueue/Tests/Client/MessageTest.php, pkg/enqueue/Tests/Client/NullDriverTest.php, pkg/enqueue/Tests/Client/RpcClientTest.php, pkg/enqueue/Tests/Consumption/Extension/ReplyExtensionTest.php, pkg/enqueue/Tests/Functional/Client/RpcClientTest.php, pkg/enqueue/Tests/Rpc/PromiseTest.php, pkg/enqueue/Tests/Rpc/TimeoutExceptionTest.php, pkg/stomp/Client/StompDriver.php, pkg/stomp/Tests/Client/RabbitMqStompDriverTest.php, pkg/stomp/Tests/Client/StompDriverTest.php
It provides a same level of abstraction as client's producer.
TODO:
=> [client] Add RpcClient on client level.

docs/bundle/async_events.md, pkg/enqueue-bundle/Events/DependencyInjection/AsyncEventsPass.php, pkg/enqueue-bundle/Tests/Functional/App/TestAsyncSubscriber.php, pkg/enqueue-bundle/Tests/Functional/App/config/config.yml, pkg/enqueue-bundle/Tests/Functional/Events/AsyncProcessorTest.php, pkg/enqueue-bundle/Tests/Functional/Events/AsyncSubscriberTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/94
=> Symfony. Async event subscriber.

pkg/amqp-ext/AmqpConsumer.php
hotfix for https://github.com/php-enqueue/enqueue-dev/issues/110
=> [amqp] Switch to AMQP' basic.get till the issue with basic.consume is solved.

pkg/amqp-ext/AmqpConsumer.php
- usleep 100ms was added
ref https://github.com/php-enqueue/enqueue-dev/issues/116
=> [amqp] Fixes high CPU consumption when basic get is used

pkg/amqp-ext/Symfony/AmqpTransportFactory.php, pkg/amqp-ext/Tests/Symfony/AmqpTransportFactoryTest.php, pkg/amqp-ext/Tests/Symfony/RabbitMqAmqpTransportFactoryTest.php
ref https://github.com/php-enqueue/enqueue-dev/issues/116
=> [amqp] Add 'receive_method' to amqp transport factory.

pkg/dbal/DbalContext.php, pkg/dbal/Tests/DbalContextTest.php
see https://github.com/php-enqueue/enqueue-dev/issues/121
=> fix dbal polling interval configuration option

pkg/amqp-ext/AmqpConsumer.php, pkg/amqp-ext/Symfony/AmqpTransportFactory.php, pkg/amqp-ext/Symfony/RabbitMqAmqpTransportFactory.php, pkg/amqp-ext/Tests/Symfony/AmqpTransportFactoryTest.php, pkg/amqp-ext/Tests/Symfony/RabbitMqAmqpTransportFactoryTest.php, pkg/amqp-lib/AmqpConsumer.php, pkg/amqp-lib/Symfony/AmqpLibTransportFactory.php, pkg/amqp-lib/Symfony/RabbitMqAmqpLibTransportFactory.php, pkg/amqp-lib/Tests/Symfony/AmqpLibTransportFactoryTest.php, pkg/amqp-lib/Tests/Symfony/RabbitMqAmqpLibTransportFactoryTest.php, pkg/enqueue-bundle/EnqueueBundle.php, pkg/enqueue-bundle/Tests/Unit/EnqueueBundleTest.php, pkg/enqueue/Client/Amqp/AmqpDriver.php, pkg/enqueue/Client/Amqp/RabbitMqDriver.php, pkg/enqueue/Tests/Client/Amqp/AmqpDriverTest.php, pkg/enqueue/Tests/Client/Amqp/RabbitMqDriverTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/143, https://github.com/php-enqueue/enqueue-dev/issues/142
=> amqp interop client

pkg/enqueue-bundle/DependencyInjection/Configuration.php, pkg/enqueue-bundle/DependencyInjection/EnqueueExtension.php, pkg/enqueue-bundle/Tests/Unit/DependencyInjection/ConfigurationTest.php, pkg/rdkafka/Tests/Spec/RdKafkaSendToAndReceiveFromTopicTest.php
https://github.com/php-enqueue/enqueue-dev/pull/168 + tests
=> Bundle disable async events by default

pkg/fs/FsConsumer.php, pkg/fs/Tests/Functional/FsConsumerTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/170
=> [fs] fix bug that happens with specific message length.

pkg/enqueue/Client/ConsumptionExtension/DelayRedeliveredMessageExtension.php, pkg/enqueue/Tests/Client/ConsumptionExtension/DelayRedeliveredMessageExtensionTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/41
=> [client] DelayRedeliveredMessageExtension. Add reject reason.

pkg/enqueue-bundle/Profiler/MessageQueueCollector.php, pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig, pkg/enqueue-bundle/Tests/Unit/Profiler/MessageQueueCollectorTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/211
=> [bundle][profiler] Fix array to string conversion notice.

.travis.yml, pkg/fs/FsContext.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/166
=> Fs do not throw error on user deprecate

pkg/enqueue/Symfony/Client/ConsumeMessagesCommand.php, pkg/enqueue/Tests/Symfony/Client/ConsumeMessagesCommandTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/216
=> [client] Add --skip option to consume command.

pkg/enqueue-bundle/Resources/views/Profiler/panel.html.twig
=> [bundle] streamline profiler view when no messages were sent

pkg/redis/PhpRedis.php, pkg/redis/RedisConnectionFactory.php, pkg/redis/Symfony/RedisTransportFactory.php, pkg/redis/Tests/RedisConnectionFactoryConfigTest.php, pkg/redis/Tests/Symfony/RedisTransportFactoryTest.php
add configuration to use custom redis database index
reference
https://github.com/nrk/predis/wiki/Connection-Parameters
https://github.com/phpredis/phpredis/blob/develop/README.markdown#select
=> [Redis] add custom database index

docs/cookbook/symfony/how-to-change-consume-command-logger.md, docs/index.md, pkg/enqueue/Consumption/Extension/LoggerExtension.php, pkg/enqueue/Tests/Consumption/Extension/LoggerExtensionTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/287
=> [consumption] Add ability to overwrite logger.

README.md, docs/index.md, docs/yii/amqp_driver.md
ref https://github.com/yiisoft/yii2-queue/pull/158
=> [doc] yii2-queue amqp driver

pkg/enqueue/Consumption/QueueConsumer.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/303
=> [consumption] Fix signal handling when AMQP is used.

pkg/enqueue/Consumption/QueueConsumer.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/311
=> [consumption] Make QueueConsumer final

pkg/gearman/.travis.yml, pkg/gearman/composer.json
Fixes https://github.com/php-enqueue/enqueue-dev/issues/270
=> Gearman PHP 7 support

pkg/dbal/DbalContext.php, pkg/dbal/DbalMessage.php, pkg/dbal/Tests/DbalContextTest.php, pkg/dbal/Tests/DbalMessageTest.php
=> [dbal] Consumer never fetches messages ordered by published time

pkg/sqs/SqsConnectionFactory.php, pkg/sqs/Tests/SqsConnectionFactoryConfigTest.php, pkg/sqs/Tests/SqsConnectionFactoryTest.php
https://github.com/php-enqueue/enqueue-dev/issues/352
=> Added endpoint configuration and updated the tests

pkg/enqueue/Symfony/DefaultTransportFactory.php, pkg/enqueue/Tests/Symfony/DefaultTransportFactoryTest.php
fix https://github.com/php-enqueue/enqueue-dev/issues/356
=> [bundle] DefaultTransportFactory should accept DSN like foo:

pkg/dbal/DbalConsumer.php
Everything is described on this issue: https://github.com/php-enqueue/enqueue-dev/issues/360
=> Fix wrong argument type

pkg/enqueue-bundle/Resources/config/client.yml, pkg/enqueue-bundle/Tests/Unit/DependencyInjection/EnqueueExtensionTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/376
=> [bundle] add producer interface alias.

pkg/simple-client/SimpleClient.php, pkg/simple-client/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/386
=> [client] Simple Client should not depend on amqp-ext.

docs/quick_tour.md
=> Fix a tiny little typo in documentation

docs/transport/sqs.md
It's a update for the SQS doc related to the issue https://github.com/php-enqueue/enqueue-dev/issues/481
=> Update SQS DSN doc sample with mention urlencode

pkg/sqs/SqsProducer.php, pkg/sqs/Tests/SqsProducerTest.php
=> Prevent SqsProducer from sending messages with empty bodies

pkg/amqp-bunny/AmqpContext.php, pkg/amqp-bunny/composer.json, pkg/amqp-ext/AmqpContext.php, pkg/amqp-ext/composer.json, pkg/amqp-lib/AmqpContext.php, pkg/amqp-lib/composer.json, pkg/amqp-tools/SubscriptionConsumer.php, pkg/amqp-tools/Tests/SubscriptionConsumerTest.php, pkg/amqp-tools/composer.json, pkg/enqueue-bundle/Resources/config/services.yml, pkg/enqueue-bundle/composer.json, pkg/enqueue/Consumption/FallbackSubscriptionConsumer.php, pkg/enqueue/Consumption/QueueConsumer.php, pkg/enqueue/Tests/Consumption/FallbackSubscriptionConsumerTest.php
Improves a lot non-AMQP transports (such as SQS, Doctrine DBAL, MongoDB) multi queue consumption.
=> Improve multi queue consumption.

pkg/dbal/DbalContext.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/465
=> [dbla] Add index, fix performance issue. 

pkg/dbal/Client/DbalDriver.php, pkg/dbal/Tests/Client/DbalDriverTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/418
=> [BC break][dbal] Fix time conversion in DbalDriver.

pkg/redis/PRedis.php
As requested in https://github.com/php-enqueue/enqueue-dev/pull/497#issuecomment-414077792.
Unfortunately I'm very new to enqueue so I need some guidance here maybe on where to add tests for that 😄
=> Fixed password auth for predis

pkg/enqueue/Consumption/QueueConsumer.php
Remove bool typehint for php < 7 supports
=> Remove bool typehint for php < 7 supports

pkg/redis/RedisConnectionFactory.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/525
=> [redis] Revert timeout change.

pkg/enqueue/Consumption/QueueConsumer.php
=> enableSubscriptionConsumer setter

pkg/stomp/StompContext.php, pkg/stomp/Tests/StompConnectionFactoryTest.php, pkg/stomp/Tests/StompContextTest.php
=> [STOMP] make getStomp public

pkg/rdkafka/RdKafkaConnectionFactory.php, pkg/rdkafka/Tests/RdKafkaConnectionFactoryTest.php
see https://github.com/php-enqueue/enqueue-dev/pull/561
=> Fixing kafka default configuration

docs/transport/amqp.md
I assume this comment was copied from the previous section but not fully changed.
=> Fix comment about queue deletion

pkg/enqueue/Symfony/Client/ConsumeCommand.php, pkg/enqueue/Symfony/Client/DependencyInjection/AnalyzeRouteCollectionPass.php, pkg/enqueue/Tests/Symfony/Client/ConsumeCommandTest.php, pkg/enqueue/Tests/Symfony/Client/DependencyInjection/AnalyzeRouteCollectionPassTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/608
=> [client][bundle] Take queue prefix into account while queue binding.

pkg/enqueue/Symfony/Client/Meta/QueuesCommand.php, pkg/enqueue/Symfony/Client/Meta/TopicsCommand.php
=> Fixed headline

pkg/enqueue-bundle/Consumption/Extension/DoctrinePingConnectionExtension.php
(cherry picked from commit 72d4097)
=> Fix ping to check each connection, not only first one

pkg/amqp-bunny/composer.json, pkg/amqp-ext/composer.json, pkg/amqp-lib/composer.json, pkg/async-command/composer.json, pkg/async-event-dispatcher/composer.json, pkg/enqueue-bundle/composer.json, pkg/enqueue/composer.json, pkg/fs/composer.json, pkg/gps/composer.json, pkg/job-queue/composer.json, pkg/monitoring/composer.json, pkg/redis/composer.json, pkg/simple-client/composer.json, pkg/sqs/composer.json, pkg/stomp/composer.json, pkg/wamp/composer.json
fixes https://github.com/php-enqueue/enqueue-dev/issues/659
=> Allow installing stable dependencies.

pkg/dsn/Dsn.php
Was reviewing the dsn class since I plan to use it and I saw some commented code. If this was intentional just close the PR.
Looks like a nice lib, thank you!
=> [dsn] remove commented out code

docs/client/quick_tour.md, docs/quick_tour.md, pkg/enqueue-bundle/Tests/Functional/UseCasesTest.php, pkg/enqueue/Symfony/Client/SimpleConsumeCommand.php, pkg/enqueue/Symfony/Client/SimpleProduceCommand.php, pkg/enqueue/Symfony/Client/SimpleRoutesCommand.php, pkg/enqueue/Symfony/Client/SimpleSetupBrokerCommand.php, pkg/enqueue/Symfony/Consumption/SimpleConsumeCommand.php, pkg/enqueue/Tests/Symfony/Client/SimpleConsumeCommandTest.php, pkg/enqueue/Tests/Symfony/Client/SimpleProduceCommandTest.php, pkg/enqueue/Tests/Symfony/Client/SimpleRoutesCommandTest.php, pkg/enqueue/Tests/Symfony/Client/SimpleSetupBrokerCommandTest.php, pkg/enqueue/Tests/Symfony/Consumption/SimpleConsumeCommandTest.php, pkg/simple-client/SimpleClient.php, pkg/simple-client/Tests/Functional/SimpleClientTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/681, https://github.com/php-enqueue/enqueue-dev/issues/682
=> Add commands for single transport\client with typed arguments.

pkg/job-queue/JobProcessor.php, pkg/job-queue/Tests/JobProcessorTest.php
fixes https://github.com/php-enqueue/enqueue-dev/issues/729
=> fix job status processor

docs/transport/snsqs.md
Was: `composer require enqueue/sqs` should be: `composer require enqueue/snsqs`
=> Corrected the installation part in the docs/transport/snsqs.md

pkg/enqueue/Consumption/QueueConsumer.php
default timeout is 10000 milliseconds and this constructor will not accept float
=> fix comment on QueueConsumer constructor

docs/bundle/functional_testing.md
=> better doc for traceable message producer

pkg/amqp-bunny/AmqpConnectionFactory.php
Reverts php-enqueue/enqueue-dev#820 (see #854)
=> Revert "Fix heartbeat configuration in bunny with 0 (off) value"

README.md, docs/transport/sns.md
As requested in https://github.com/php-enqueue/enqueue-dev/pull/872#discussion_r287781194
=> Add Amazon SNS documentation placeholder

docs/concepts.md, docs/index.md
We have spent some times at AssoConnect trying to understand the logic of Enqueue for using it and creating a transport for Azure Storage Queue.
There is already a lot of content in the doc but it misses an explanation of the key concepts. It was a pain to understand how all the classes should be used: this PR tries to fix this.
It may contain incorrect info so let me know if we have misunderstood some concepts and I'll update the PR.
=> Key concepts

pkg/amqp-tools/README.md, pkg/async-command/README.md, pkg/async-event-dispatcher/README.md, pkg/enqueue-bundle/README.md, pkg/enqueue/README.md, pkg/job-queue/README.md, pkg/simple-client/README.md, pkg/test/README.md
=> Fix documentation links

pkg/sns/composer.json, pkg/snsqs/composer.json
=> Updates dependencies requirements for sns(qs)

pkg/enqueue/Client/Resources.php
I could not really configure SNS without this.
=> Adding generic driver for schema SNS

pkg/amqp-lib/AmqpSubscriptionConsumer.php, pkg/amqp-lib/composer.json
.. and require more recent library version
=> Fix deprecated heartbeat check method

pkg/dbal/DbalConsumerHelperTrait.php
swap redelivered flag from in-line sql constant to parameter to better work with MS-SQL server
=> #977 - Fix issues with MS SQL server and dbal transport

pkg/rdkafka/RdKafkaConsumer.php
=> Prefer early returns in consumer code

docs/bundle/consumption_extension.md
=> Add extension tag parameter note

pkg/dbal/composer.json, pkg/enqueue/composer.json, pkg/monitoring/composer.json, pkg/redis/composer.json
Continue of #1043 . I hope if this PR pass code review, will be released.
=> Allow to install ramsey/uuid:^4

pkg/mongodb/MongodbConsumer.php
=> fix(MongoDB) Redelivery not working (fixes #1077)

pkg/amqp-lib/AmqpContext.php
Solves binding `Queue` with `Headers Exchange` using custom arguments.
=> Solves binding Headers Exchange with Queue using custom arguments

.github/workflows/ci.yml, bin/git-find-changed-php-files.sh
Working CI demo: https://github.com/andrewmy/enqueue-dev/pull/1
Fails the same pubsub tests as travis here 😅
=> Add GitHub Action CI

pkg/gearman/GearmanConsumer.php
New PR with clean history following discussion in #1141
=> register worker callback only once, move to constructor

pkg/snsqs/SnsQsContext.php
Sorry, I missed that I hadn't passed the arg in the previous PR
=> Add in missing arg

pkg/rdkafka/RdKafkaConsumer.php
Details in issue: https://github.com/php-enqueue/enqueue-dev/issues/1185
=> Added getter for offset field in RdKafkaConsumer class

pkg/enqueue-bundle/Profiler/AbstractMessageQueueCollector.php, pkg/enqueue/Symfony/Client/FlushSpoolProducerListener.php
=> Fix types for Symfony 5.4

pkg/job-queue/composer.json
Add version ^3.0 for doctine dbal
=> chore: Update dependency dbal

.github/workflows/ci.yml
Symfony 6.3 is released, let's test on it too.
=> Add Symfony 6.3 to CI

composer.json, pkg/amqp-ext/composer.json
Created PR based on this: https://github.com/php-enqueue/amqp-ext/pull/2 to main repo
fixes: #1313
=> feat: update ext-amqp to use v2

composer.json, pkg/amqp-bunny/composer.json, pkg/amqp-ext/composer.json, pkg/amqp-lib/composer.json, pkg/amqp-tools/composer.json, pkg/async-command/composer.json, pkg/async-event-dispatcher/composer.json, pkg/dbal/composer.json, pkg/dsn/composer.json, pkg/enqueue/composer.json, pkg/fs/composer.json, pkg/gearman/composer.json, pkg/gps/composer.json, pkg/job-queue/composer.json, pkg/mongodb/composer.json, pkg/monitoring/composer.json, pkg/null/composer.json, pkg/pheanstalk/composer.json, pkg/rdkafka/composer.json, pkg/redis/composer.json, pkg/simple-client/composer.json, pkg/sns/composer.json, pkg/snsqs/composer.json, pkg/sqs/composer.json, pkg/stomp/composer.json, pkg/wamp/composer.json
Updating composer.json in pkg directory to correctly reflect the supported versions of PHP
see #1378, #1381
=> Fix: Updating composer
